/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './login';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/forms/src/form_builder';
import * as import10 from '../../providers/users/users.service';
import * as import11 from 'ionic-angular/components/loading/loading';
import * as import12 from 'ionic-angular/components/alert/alert';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import19 from '../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.ngfactory';
import * as import20 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import22 from '@angular/core/src/linker/query_list';
import * as import23 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import24 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import25 from '../../node_modules/@angular/forms/src/directives/reactive_directives/form_control_name.ngfactory';
import * as import26 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import27 from '../../components/control-message/control-message.ngfactory';
import * as import28 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import29 from 'ionic-angular/config/config';
import * as import30 from '@angular/core/src/linker/element_ref';
import * as import31 from 'ionic-angular/navigation/view-controller';
import * as import32 from 'ionic-angular/components/app/app';
import * as import33 from 'ionic-angular/components/toolbar/toolbar';
import * as import34 from 'ionic-angular/util/keyboard';
import * as import35 from '@angular/core/src/zone/ng_zone';
import * as import36 from 'ionic-angular/components/tabs/tabs';
import * as import37 from 'ionic-angular/util/form';
import * as import38 from 'ionic-angular/components/item/item-reorder';
import * as import39 from 'ionic-angular/platform/platform';
import * as import40 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import41 from 'ionic-angular/components/navbar/navbar';
import * as import42 from 'ionic-angular/components/icon/icon';
import * as import43 from 'ionic-angular/components/label/label';
import * as import44 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import45 from '@angular/forms/src/directives/ng_control';
import * as import46 from '@angular/forms/src/directives/ng_control_status';
import * as import47 from 'ionic-angular/components/input/input';
import * as import48 from 'ionic-angular/components/item/item';
import * as import49 from '../../components/control-message/control-message';
import * as import50 from 'ionic-angular/components/button/button';
import * as import51 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import52 from '@angular/forms/src/directives/control_container';
import * as import53 from 'ionic-angular/components/content/content';
export class Wrapper_LoginPage {
  context:import0.LoginPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any) {
    this.changed = false;
    this.context = new import0.LoginPage(p0,p1,p2,p3,p4);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_LoginPage_Host:import2.RenderComponentType = (null as any);
class _View_LoginPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _LoginPage_0_4:Wrapper_LoginPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginPage_Host0,renderType_LoginPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-login',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_LoginPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LoginPage_0_4 = new Wrapper_LoginPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.FormBuilder),this.parentInjector.get(import10.UsersService),this.parentInjector.get(import11.LoadingController),this.parentInjector.get(import12.AlertController));
    this._appEl_0.initComponent(this._LoginPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._LoginPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.LoginPage) && (0 === requestNodeIndex))) { return this._LoginPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._LoginPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_LoginPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_LoginPage_Host === (null as any))) { (renderType_LoginPage_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_LoginPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const LoginPageNgFactory:import14.ComponentFactory<import0.LoginPage> = new import14.ComponentFactory<import0.LoginPage>('page-login',viewFactory_LoginPage_Host0,import0.LoginPage);
const styles_LoginPage:any[] = ([] as any[]);
var renderType_LoginPage:import2.RenderComponentType = (null as any);
class _View_LoginPage0 extends import1.AppView<import0.LoginPage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import15.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import16.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _ToolbarTitle_5_4:import17.Wrapper_ToolbarTitle;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import3.AppElement;
  _Content_10_4:import18.Wrapper_Content;
  _text_11:any;
  _el_12:any;
  _FormGroupDirective_12_3:import19.Wrapper_FormGroupDirective;
  _ControlContainer_12_4:any;
  _NgControlStatusGroup_12_5:import20.Wrapper_NgControlStatusGroup;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import3.AppElement;
  _Item_14_4:import21.Wrapper_Item;
  _ItemContent_14_5:import21.Wrapper_ItemContent;
  _query_Label_14_0:import22.QueryList<any>;
  _query_Button_14_1:import22.QueryList<any>;
  _query_Icon_14_2:import22.QueryList<any>;
  _text_15:any;
  _el_16:any;
  _Label_16_3:import23.Wrapper_Label;
  _text_17:any;
  _el_18:any;
  _Icon_18_3:import24.Wrapper_Icon;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  /*private*/ _appEl_21:import3.AppElement;
  _FormControlName_21_4:import25.Wrapper_FormControlName;
  _NgControl_21_5:any;
  _NgControlStatus_21_6:import20.Wrapper_NgControlStatus;
  _TextInput_21_7:import26.Wrapper_TextInput;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  /*private*/ _appEl_24:import3.AppElement;
  _ControlMessageComponent_24_4:import27.Wrapper_ControlMessageComponent;
  _text_25:any;
  _el_26:any;
  /*private*/ _appEl_26:import3.AppElement;
  _Item_26_4:import21.Wrapper_Item;
  _ItemContent_26_5:import21.Wrapper_ItemContent;
  _query_Label_26_0:import22.QueryList<any>;
  _query_Button_26_1:import22.QueryList<any>;
  _query_Icon_26_2:import22.QueryList<any>;
  _text_27:any;
  _el_28:any;
  _Label_28_3:import23.Wrapper_Label;
  _text_29:any;
  _el_30:any;
  _Icon_30_3:import24.Wrapper_Icon;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  /*private*/ _appEl_33:import3.AppElement;
  _FormControlName_33_4:import25.Wrapper_FormControlName;
  _NgControl_33_5:any;
  _NgControlStatus_33_6:import20.Wrapper_NgControlStatus;
  _TextInput_33_7:import26.Wrapper_TextInput;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  /*private*/ _appEl_36:import3.AppElement;
  _ControlMessageComponent_36_4:import27.Wrapper_ControlMessageComponent;
  _text_37:any;
  _el_38:any;
  /*private*/ _appEl_38:import3.AppElement;
  _Button_38_4:import28.Wrapper_Button;
  _text_39:any;
  _el_40:any;
  _Icon_40_3:import24.Wrapper_Icon;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  /*private*/ _appEl_45:import3.AppElement;
  _Button_45_4:import28.Wrapper_Button;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _Footer_48_3:import15.Wrapper_Footer;
  _text_49:any;
  _el_50:any;
  /*private*/ _appEl_50:import3.AppElement;
  _Button_50_4:import28.Wrapper_Button;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_39:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginPage0,renderType_LoginPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import15.Wrapper_Header(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import31.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n\n    ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this.renderer.setElementAttribute(this._el_3,'color','primary');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import16.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import16.Wrapper_Navbar(this.parentInjector.get(import32.App),this.parentInjector.get(import31.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_5 = new import3.AppElement(5,3,this,this._el_5);
    var compView_5:any = import17.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(5),this._appEl_5);
    this._ToolbarTitle_5_4 = new import17.Wrapper_ToolbarTitle(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import33.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._appEl_5.initComponent(this._ToolbarTitle_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'weCollab ',(null as any));
    compView_5.create(this._ToolbarTitle_5_4.context,[([] as any[]).concat([this._text_6])],(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_4,
        this._el_5,
        this._text_7
      ]
      )
    ]
    ,(null as any));
    this._text_8 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_10 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_10,'padding','');
    this._appEl_10 = new import3.AppElement(10,(null as any),this,this._el_10);
    var compView_10:any = import18.viewFactory_Content0(this.viewUtils,this.injector(10),this._appEl_10);
    this._Content_10_4 = new import18.Wrapper_Content(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import32.App),this.parentInjector.get(import34.Keyboard),this.parentInjector.get(import35.NgZone),this.parentInjector.get(import31.ViewController,(null as any)),this.parentInjector.get(import36.Tabs,(null as any)));
    this._appEl_10.initComponent(this._Content_10_4.context,([] as any[]),compView_10);
    this._text_11 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'form',(null as any));
    this._FormGroupDirective_12_3 = new import19.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_12_4 = this._FormGroupDirective_12_3.context;
    this._NgControlStatusGroup_12_5 = new import20.Wrapper_NgControlStatusGroup(this._ControlContainer_12_4);
    this._text_13 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','item item-block');
    this._appEl_14 = new import3.AppElement(14,12,this,this._el_14);
    var compView_14:any = import21.viewFactory_Item0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Item_14_4 = new import21.Wrapper_Item(this.parentInjector.get(import37.Form),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import38.ItemReorder,(null as any)));
    this._ItemContent_14_5 = new import21.Wrapper_ItemContent();
    this._query_Label_14_0 = new import22.QueryList<any>();
    this._query_Button_14_1 = new import22.QueryList<any>();
    this._query_Icon_14_2 = new import22.QueryList<any>();
    this._appEl_14.initComponent(this._Item_14_4.context,([] as any[]),compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_16,'floating','');
    this._Label_16_3 = new import23.Wrapper_Label(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_16),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n                ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_18,'item-left','');
    this.renderer.setElementAttribute(this._el_18,'name','mail');
    this.renderer.setElementAttribute(this._el_18,'role','img');
    this._Icon_18_3 = new import24.Wrapper_Icon(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_18),this.renderer);
    this._text_19 = this.renderer.createText(this._el_16,'\n                Email',(null as any));
    this._text_20 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_21 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_21,'autocapitalize','off');
    this.renderer.setElementAttribute(this._el_21,'formControlName','email');
    this.renderer.setElementAttribute(this._el_21,'spellcheck','false');
    this.renderer.setElementAttribute(this._el_21,'type','email');
    this._appEl_21 = new import3.AppElement(21,14,this,this._el_21);
    var compView_21:any = import26.viewFactory_TextInput0(this.viewUtils,this.injector(21),this._appEl_21);
    this._FormControlName_21_4 = new import25.Wrapper_FormControlName(this._ControlContainer_12_4,(null as any),(null as any),(null as any));
    this._NgControl_21_5 = this._FormControlName_21_4.context;
    this._NgControlStatus_21_6 = new import20.Wrapper_NgControlStatus(this._NgControl_21_5);
    this._TextInput_21_7 = new import26.Wrapper_TextInput(this.parentInjector.get(import29.Config),this.parentInjector.get(import37.Form),this._Item_14_4.context,this.parentInjector.get(import32.App),this.parentInjector.get(import39.Platform),new import30.ElementRef(this._el_21),this.renderer,this._Content_10_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_21_5);
    this._appEl_21.initComponent(this._TextInput_21_7.context,([] as any[]),compView_21);
    compView_21.create(this._TextInput_21_7.context,([] as any[]),(null as any));
    this._text_22 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._query_Label_14_0.reset([this._Label_16_3.context]);
    this._Item_14_4.context.contentLabel = this._query_Label_14_0.first;
    compView_14.create(this._Item_14_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_16]),
      ([] as any[]).concat([
        this._text_15,
        this._text_20,
        this._text_22
      ]
      ),
      ([] as any[]).concat([this._el_21]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_23 = this.renderer.createText(this._el_12,'\n\n        ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_12,'control-message',(null as any));
    this._appEl_24 = new import3.AppElement(24,12,this,this._el_24);
    var compView_24:any = import27.viewFactory_ControlMessageComponent0(this.viewUtils,this.injector(24),this._appEl_24);
    this._ControlMessageComponent_24_4 = new import27.Wrapper_ControlMessageComponent();
    this._appEl_24.initComponent(this._ControlMessageComponent_24_4.context,([] as any[]),compView_24);
    compView_24.create(this._ControlMessageComponent_24_4.context,([] as any[]),(null as any));
    this._text_25 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','item item-block');
    this._appEl_26 = new import3.AppElement(26,12,this,this._el_26);
    var compView_26:any = import21.viewFactory_Item0(this.viewUtils,this.injector(26),this._appEl_26);
    this._Item_26_4 = new import21.Wrapper_Item(this.parentInjector.get(import37.Form),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_26),this.renderer,this.parentInjector.get(import38.ItemReorder,(null as any)));
    this._ItemContent_26_5 = new import21.Wrapper_ItemContent();
    this._query_Label_26_0 = new import22.QueryList<any>();
    this._query_Button_26_1 = new import22.QueryList<any>();
    this._query_Icon_26_2 = new import22.QueryList<any>();
    this._appEl_26.initComponent(this._Item_26_4.context,([] as any[]),compView_26);
    this._text_27 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_28 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_28,'floating','');
    this._Label_28_3 = new import23.Wrapper_Label(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_28),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'\n                ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_28,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_30,'item-left','');
    this.renderer.setElementAttribute(this._el_30,'name','lock');
    this.renderer.setElementAttribute(this._el_30,'role','img');
    this._Icon_30_3 = new import24.Wrapper_Icon(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_30),this.renderer);
    this._text_31 = this.renderer.createText(this._el_28,' Password',(null as any));
    this._text_32 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_33 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_33,'formControlName','password');
    this.renderer.setElementAttribute(this._el_33,'type','password');
    this._appEl_33 = new import3.AppElement(33,26,this,this._el_33);
    var compView_33:any = import26.viewFactory_TextInput0(this.viewUtils,this.injector(33),this._appEl_33);
    this._FormControlName_33_4 = new import25.Wrapper_FormControlName(this._ControlContainer_12_4,(null as any),(null as any),(null as any));
    this._NgControl_33_5 = this._FormControlName_33_4.context;
    this._NgControlStatus_33_6 = new import20.Wrapper_NgControlStatus(this._NgControl_33_5);
    this._TextInput_33_7 = new import26.Wrapper_TextInput(this.parentInjector.get(import29.Config),this.parentInjector.get(import37.Form),this._Item_26_4.context,this.parentInjector.get(import32.App),this.parentInjector.get(import39.Platform),new import30.ElementRef(this._el_33),this.renderer,this._Content_10_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_33_5);
    this._appEl_33.initComponent(this._TextInput_33_7.context,([] as any[]),compView_33);
    compView_33.create(this._TextInput_33_7.context,([] as any[]),(null as any));
    this._text_34 = this.renderer.createText((null as any),'\n\n        ',(null as any));
    this._query_Label_26_0.reset([this._Label_28_3.context]);
    this._Item_26_4.context.contentLabel = this._query_Label_26_0.first;
    compView_26.create(this._Item_26_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_28]),
      ([] as any[]).concat([
        this._text_27,
        this._text_32,
        this._text_34
      ]
      ),
      ([] as any[]).concat([this._el_33]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_35 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_12,'control-message',(null as any));
    this._appEl_36 = new import3.AppElement(36,12,this,this._el_36);
    var compView_36:any = import27.viewFactory_ControlMessageComponent0(this.viewUtils,this.injector(36),this._appEl_36);
    this._ControlMessageComponent_36_4 = new import27.Wrapper_ControlMessageComponent();
    this._appEl_36.initComponent(this._ControlMessageComponent_36_4.context,([] as any[]),compView_36);
    compView_36.create(this._ControlMessageComponent_36_4.context,([] as any[]),(null as any));
    this._text_37 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_12,'button',(null as any));
    this.renderer.setElementAttribute(this._el_38,'full','');
    this.renderer.setElementAttribute(this._el_38,'icon-left','');
    this.renderer.setElementAttribute(this._el_38,'ion-button','');
    this.renderer.setElementAttribute(this._el_38,'item-right','');
    this.renderer.setElementAttribute(this._el_38,'type','Submit');
    this._appEl_38 = new import3.AppElement(38,12,this,this._el_38);
    var compView_38:any = import28.viewFactory_Button0(this.viewUtils,this.injector(38),this._appEl_38);
    this._Button_38_4 = new import28.Wrapper_Button((null as any),'',this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_38),this.renderer);
    this._appEl_38.initComponent(this._Button_38_4.context,([] as any[]),compView_38);
    this._text_39 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_40 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_40,'item-left','');
    this.renderer.setElementAttribute(this._el_40,'name','person');
    this.renderer.setElementAttribute(this._el_40,'role','img');
    this._Icon_40_3 = new import24.Wrapper_Icon(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_40),this.renderer);
    this._text_41 = this.renderer.createText(this._el_40,' ',(null as any));
    this._text_42 = this.renderer.createText((null as any),'\n            Sign in\n        ',(null as any));
      compView_38.create(this._Button_38_4.context,[([] as any[]).concat([
        this._text_39,
        this._el_40,
        this._text_42
      ]
    )],(null as any));
    this._text_43 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._text_44 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_45 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_45,'clear','');
    this.renderer.setElementAttribute(this._el_45,'ion-button','');
    this.renderer.setElementAttribute(this._el_45,'ion-left','');
    this.renderer.setElementAttribute(this._el_45,'small','');
    this._appEl_45 = new import3.AppElement(45,10,this,this._el_45);
    var compView_45:any = import28.viewFactory_Button0(this.viewUtils,this.injector(45),this._appEl_45);
    this._Button_45_4 = new import28.Wrapper_Button((null as any),'',this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_45),this.renderer);
    this._appEl_45.initComponent(this._Button_45_4.context,([] as any[]),compView_45);
    this._text_46 = this.renderer.createText((null as any),'Forgot Password?',(null as any));
    compView_45.create(this._Button_45_4.context,[([] as any[]).concat([this._text_46])],(null as any));
    this._text_47 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_48 = this.renderer.createElement((null as any),'ion-footer',(null as any));
    this.renderer.setElementAttribute(this._el_48,'no-shadow','');
    this._Footer_48_3 = new import15.Wrapper_Footer(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_48),this.renderer,this.parentInjector.get(import31.ViewController,(null as any)));
    this._text_49 = this.renderer.createText(this._el_48,'\n        ',(null as any));
    this._el_50 = this.renderer.createElement(this._el_48,'button',(null as any));
    this.renderer.setElementAttribute(this._el_50,'block','');
    this.renderer.setElementAttribute(this._el_50,'clear','');
    this.renderer.setElementAttribute(this._el_50,'ion-button','');
    this.renderer.setElementAttribute(this._el_50,'small','');
    this._appEl_50 = new import3.AppElement(50,48,this,this._el_50);
    var compView_50:any = import28.viewFactory_Button0(this.viewUtils,this.injector(50),this._appEl_50);
    this._Button_50_4 = new import28.Wrapper_Button((null as any),'',this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_50),this.renderer);
    this._appEl_50.initComponent(this._Button_50_4.context,([] as any[]),compView_50);
    this._text_51 = this.renderer.createText((null as any),'Join Now...',(null as any));
    compView_50.create(this._Button_50_4.context,[([] as any[]).concat([this._text_51])],(null as any));
    this._text_52 = this.renderer.createText(this._el_48,'\n    ',(null as any));
    this._text_53 = this.renderer.createText((null as any),'\n',(null as any));
    compView_10.create(this._Content_10_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_11,
        this._el_12,
        this._text_44,
        this._el_45,
        this._text_47,
        this._el_48,
        this._text_53
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_12,'ngSubmit',this.eventHandler(this._handle_ngSubmit_12_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_12,'submit',this.eventHandler(this._handle_submit_12_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_12,'reset',this.eventHandler(this._handle_reset_12_2.bind(this)));
    const subscription_0:any = this._FormGroupDirective_12_3.context.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_12_0.bind(this)));
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_45,'click',this.eventHandler(this._handle_click_45_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_50,'click',this.eventHandler(this._handle_click_50_0.bind(this)));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._text_53
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import40.ToolbarTitle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ToolbarTitle_5_4.context; }
    if (((token === import41.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Navbar_3_4.context; }
    if (((token === import33.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Header_1_3.context; }
    if (((token === import42.Icon) && (18 === requestNodeIndex))) { return this._Icon_18_3.context; }
    if (((token === import43.Label) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._Label_16_3.context; }
    if (((token === import44.FormControlName) && (21 === requestNodeIndex))) { return this._FormControlName_21_4.context; }
    if (((token === import45.NgControl) && (21 === requestNodeIndex))) { return this._NgControl_21_5; }
    if (((token === import46.NgControlStatus) && (21 === requestNodeIndex))) { return this._NgControlStatus_21_6.context; }
    if (((token === import47.TextInput) && (21 === requestNodeIndex))) { return this._TextInput_21_7.context; }
    if (((token === import48.Item) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Item_14_4.context; }
    if (((token === import48.ItemContent) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._ItemContent_14_5.context; }
    if (((token === import49.ControlMessageComponent) && (24 === requestNodeIndex))) { return this._ControlMessageComponent_24_4.context; }
    if (((token === import42.Icon) && (30 === requestNodeIndex))) { return this._Icon_30_3.context; }
    if (((token === import43.Label) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Label_28_3.context; }
    if (((token === import44.FormControlName) && (33 === requestNodeIndex))) { return this._FormControlName_33_4.context; }
    if (((token === import45.NgControl) && (33 === requestNodeIndex))) { return this._NgControl_33_5; }
    if (((token === import46.NgControlStatus) && (33 === requestNodeIndex))) { return this._NgControlStatus_33_6.context; }
    if (((token === import47.TextInput) && (33 === requestNodeIndex))) { return this._TextInput_33_7.context; }
    if (((token === import48.Item) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._Item_26_4.context; }
    if (((token === import48.ItemContent) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._ItemContent_26_5.context; }
    if (((token === import49.ControlMessageComponent) && (36 === requestNodeIndex))) { return this._ControlMessageComponent_36_4.context; }
    if (((token === import42.Icon) && ((40 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._Icon_40_3.context; }
    if (((token === import50.Button) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._Button_38_4.context; }
    if (((token === import51.FormGroupDirective) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._FormGroupDirective_12_3.context; }
    if (((token === import52.ControlContainer) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._ControlContainer_12_4; }
    if (((token === import46.NgControlStatusGroup) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._NgControlStatusGroup_12_5.context; }
    if (((token === import50.Button) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._Button_45_4.context; }
    if (((token === import50.Button) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._Button_50_4.context; }
    if (((token === import33.Footer) && ((48 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._Footer_48_3.context; }
    if (((token === import53.Content) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._Content_10_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    const currVal_0:any = 'primary';
    this._Navbar_3_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    if (this._ToolbarTitle_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    if (this._Content_10_4.detectChangesInternal(this,this._el_10,throwOnChange)) { this._appEl_10.componentView.markAsCheckOnce(); }
    const currVal_7:any = this.context.loginForm;
    this._FormGroupDirective_12_3.check_form(currVal_7,throwOnChange,false);
    this._FormGroupDirective_12_3.detectChangesInternal(this,this._el_12,throwOnChange);
    this._NgControlStatusGroup_12_5.detectChangesInternal(this,this._el_12,throwOnChange);
    if (this._Item_14_4.detectChangesInternal(this,this._el_14,throwOnChange)) { this._appEl_14.componentView.markAsCheckOnce(); }
    this._ItemContent_14_5.detectChangesInternal(this,this._el_14,throwOnChange);
    this._Label_16_3.detectChangesInternal(this,this._el_16,throwOnChange);
    const currVal_14:any = 'mail';
    this._Icon_18_3.check_name(currVal_14,throwOnChange,false);
    this._Icon_18_3.detectChangesInternal(this,this._el_18,throwOnChange);
    const currVal_16:any = 'email';
    this._FormControlName_21_4.check_name(currVal_16,throwOnChange,false);
    this._FormControlName_21_4.detectChangesInternal(this,this._el_21,throwOnChange);
    this._NgControlStatus_21_6.detectChangesInternal(this,this._el_21,throwOnChange);
    const currVal_23:any = 'email';
    this._TextInput_21_7.check_type(currVal_23,throwOnChange,false);
    this._TextInput_21_7.detectChangesInternal(this,this._el_21,throwOnChange);
    const currVal_24:any = this.context.loginForm.get('email');
    this._ControlMessageComponent_24_4.check_control(currVal_24,throwOnChange,false);
    this._ControlMessageComponent_24_4.detectChangesInternal(this,this._el_24,throwOnChange);
    if (this._Item_26_4.detectChangesInternal(this,this._el_26,throwOnChange)) { this._appEl_26.componentView.markAsCheckOnce(); }
    this._ItemContent_26_5.detectChangesInternal(this,this._el_26,throwOnChange);
    this._Label_28_3.detectChangesInternal(this,this._el_28,throwOnChange);
    const currVal_25:any = 'lock';
    this._Icon_30_3.check_name(currVal_25,throwOnChange,false);
    this._Icon_30_3.detectChangesInternal(this,this._el_30,throwOnChange);
    const currVal_27:any = 'password';
    this._FormControlName_33_4.check_name(currVal_27,throwOnChange,false);
    this._FormControlName_33_4.detectChangesInternal(this,this._el_33,throwOnChange);
    this._NgControlStatus_33_6.detectChangesInternal(this,this._el_33,throwOnChange);
    const currVal_34:any = 'password';
    this._TextInput_33_7.check_type(currVal_34,throwOnChange,false);
    this._TextInput_33_7.detectChangesInternal(this,this._el_33,throwOnChange);
    const currVal_35:any = this.context.loginForm.get('password');
    this._ControlMessageComponent_36_4.check_control(currVal_35,throwOnChange,false);
    this._ControlMessageComponent_36_4.detectChangesInternal(this,this._el_36,throwOnChange);
    const currVal_37:any = '';
    this._Button_38_4.check_full(currVal_37,throwOnChange,false);
    if (this._Button_38_4.detectChangesInternal(this,this._el_38,throwOnChange)) { this._appEl_38.componentView.markAsCheckOnce(); }
    const currVal_38:any = 'person';
    this._Icon_40_3.check_name(currVal_38,throwOnChange,false);
    this._Icon_40_3.detectChangesInternal(this,this._el_40,throwOnChange);
    const currVal_41:any = '';
    this._Button_45_4.check_small(currVal_41,throwOnChange,false);
    const currVal_42:any = '';
    this._Button_45_4.check_clear(currVal_42,throwOnChange,false);
    if (this._Button_45_4.detectChangesInternal(this,this._el_45,throwOnChange)) { this._appEl_45.componentView.markAsCheckOnce(); }
    this._Footer_48_3.detectChangesInternal(this,this._el_48,throwOnChange);
    const currVal_44:any = '';
    this._Button_50_4.check_small(currVal_44,throwOnChange,false);
    const currVal_45:any = '';
    this._Button_50_4.check_clear(currVal_45,throwOnChange,false);
    const currVal_46:any = '';
    this._Button_50_4.check_block(currVal_46,throwOnChange,false);
    if (this._Button_50_4.detectChangesInternal(this,this._el_50,throwOnChange)) { this._appEl_50.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_14_1.dirty) {
        this._query_Button_14_1.reset(([] as any[]));
        this._Item_14_4.context._buttons = this._query_Button_14_1;
        this._query_Button_14_1.notifyOnChanges();
      }
      if (this._query_Icon_14_2.dirty) {
        this._query_Icon_14_2.reset(([] as any[]));
        this._Item_14_4.context._icons = this._query_Icon_14_2;
        this._query_Icon_14_2.notifyOnChanges();
      }
      if (this._query_Button_26_1.dirty) {
        this._query_Button_26_1.reset(([] as any[]));
        this._Item_26_4.context._buttons = this._query_Button_26_1;
        this._query_Button_26_1.notifyOnChanges();
      }
      if (this._query_Icon_26_2.dirty) {
        this._query_Icon_26_2.reset(([] as any[]));
        this._Item_26_4.context._icons = this._query_Icon_26_2;
        this._query_Icon_26_2.notifyOnChanges();
      }
      this._TextInput_21_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_14_4.context.ngAfterContentInit(); }
      this._TextInput_33_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_26_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_38_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_45_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_50_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_3_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_3_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_10_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_10,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_8:any = this._NgControlStatusGroup_12_5.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_12,'ng-untouched',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_12_5.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_12,'ng-touched',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatusGroup_12_5.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_12,'ng-pristine',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatusGroup_12_5.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_12,'ng-dirty',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatusGroup_12_5.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_12,'ng-valid',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatusGroup_12_5.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_12,'ng-invalid',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_15:any = this._Icon_18_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_18,'hide',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_17:any = this._NgControlStatus_21_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_21,'ng-untouched',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_21_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_21,'ng-touched',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_21_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_21,'ng-pristine',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_21_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_21,'ng-dirty',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_21_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_21,'ng-valid',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._NgControlStatus_21_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_21,'ng-invalid',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_26:any = this._Icon_30_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_30,'hide',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_28:any = this._NgControlStatus_33_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_33,'ng-untouched',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_33_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_33,'ng-touched',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_33_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_33,'ng-pristine',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_33_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_33,'ng-dirty',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_33_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_33,'ng-valid',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this._NgControlStatus_33_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_33,'ng-invalid',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_36:boolean = !this.context.loginForm.valid;
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementProperty(this._el_38,'disabled',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_39:any = this._Icon_40_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementClass(this._el_40,'hide',currVal_39);
      this._expr_39 = currVal_39;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_18_3.context.ngOnDestroy();
    this._FormControlName_21_4.context.ngOnDestroy();
    this._TextInput_21_7.context.ngOnDestroy();
    this._Icon_30_3.context.ngOnDestroy();
    this._FormControlName_33_4.context.ngOnDestroy();
    this._TextInput_33_7.context.ngOnDestroy();
    this._Icon_40_3.context.ngOnDestroy();
    this._Content_10_4.context.ngOnDestroy();
  }
  private _handle_ngSubmit_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onSubmit(this.context.loginForm.value)) !== false);
    return (true && pd_0);
  }
  private _handle_submit_12_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_12_3.context.onSubmit($event)) !== false);
    return (true && pd_0);
  }
  private _handle_reset_12_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_12_3.context.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_click_45_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.goToRegister()) !== false);
    return (true && pd_0);
  }
  private _handle_click_50_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.goToRegister()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_LoginPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.LoginPage> {
  if ((renderType_LoginPage === (null as any))) { (renderType_LoginPage = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,styles_LoginPage,{})); }
  return new _View_LoginPage0(viewUtils,parentInjector,declarationEl);
}