/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './home';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import12 from '../../node_modules/ionic-angular/components/tabs/tabs.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/tabs/tab.ngfactory';
import * as import14 from 'ionic-angular/config/config';
import * as import15 from '@angular/core/src/linker/element_ref';
import * as import16 from 'ionic-angular/navigation/view-controller';
import * as import17 from 'ionic-angular/components/app/app';
import * as import18 from 'ionic-angular/platform/platform';
import * as import19 from 'ionic-angular/navigation/deep-linker';
import * as import20 from 'ionic-angular/util/keyboard';
import * as import21 from '@angular/core/src/zone/ng_zone';
import * as import22 from '@angular/core/src/linker/component_factory_resolver';
import * as import23 from 'ionic-angular/gestures/gesture-controller';
import * as import24 from 'ionic-angular/transitions/transition-controller';
import * as import25 from 'ionic-angular/components/toolbar/toolbar';
import * as import26 from 'ionic-angular/components/tabs/tab';
import * as import27 from 'ionic-angular/components/tabs/tabs';
export class Wrapper_HomePage {
  context:import0.HomePage;
  changed:boolean;
  constructor(p0:any) {
    this.changed = false;
    this.context = new import0.HomePage(p0);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_HomePage_Host:import2.RenderComponentType = (null as any);
class _View_HomePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _HomePage_0_4:Wrapper_HomePage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_HomePage_Host0,renderType_HomePage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-home',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HomePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HomePage_0_4 = new Wrapper_HomePage(this.parentInjector.get(import8.NavController));
    this._appEl_0.initComponent(this._HomePage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._HomePage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.HomePage) && (0 === requestNodeIndex))) { return this._HomePage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._HomePage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HomePage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_HomePage_Host === (null as any))) { (renderType_HomePage_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_HomePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const HomePageNgFactory:import10.ComponentFactory<import0.HomePage> = new import10.ComponentFactory<import0.HomePage>('page-home',viewFactory_HomePage_Host0,import0.HomePage);
const styles_HomePage:any[] = ([] as any[]);
var renderType_HomePage:import2.RenderComponentType = (null as any);
class _View_HomePage0 extends import1.AppView<import0.HomePage> {
  _el_0:any;
  _Header_0_3:import11.Wrapper_Header;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Tabs_3_4:import12.Wrapper_Tabs;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _Tab_5_4:import13.Wrapper_Tab;
  _text_6:any;
  _el_7:any;
  /*private*/ _appEl_7:import3.AppElement;
  _Tab_7_4:import13.Wrapper_Tab;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _Tab_9_4:import13.Wrapper_Tab;
  _text_10:any;
  _el_11:any;
  /*private*/ _appEl_11:import3.AppElement;
  _Tab_11_4:import13.Wrapper_Tab;
  _text_12:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_HomePage0,renderType_HomePage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import11.Wrapper_Header(this.parentInjector.get(import14.Config),new import15.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import16.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_3 = this.renderer.createElement(parentRenderNode,'ion-tabs',(null as any));
    this._appEl_3 = new import3.AppElement(3,(null as any),this,this._el_3);
    var compView_3:any = import12.viewFactory_Tabs0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Tabs_3_4 = new import12.Wrapper_Tabs(this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import16.ViewController,(null as any)),this.parentInjector.get(import17.App),this.parentInjector.get(import14.Config),new import15.ElementRef(this._el_3),this.parentInjector.get(import18.Platform),this.renderer,this.parentInjector.get(import19.DeepLinker));
    this._appEl_3.initComponent(this._Tabs_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-tab',(null as any));
    this.renderer.setElementAttribute(this._el_5,'role','tabpanel');
    this.renderer.setElementAttribute(this._el_5,'tabIcon','home');
    this.renderer.setElementAttribute(this._el_5,'tabTitle','My Services');
    this._appEl_5 = new import3.AppElement(5,3,this,this._el_5);
    var compView_5:any = import13.viewFactory_Tab0(this.viewUtils,this.injector(5),this._appEl_5);
    this._Tab_5_4 = new import13.Wrapper_Tab(this._Tabs_3_4.context,this.parentInjector.get(import17.App),this.parentInjector.get(import14.Config),this.parentInjector.get(import20.Keyboard),new import15.ElementRef(this._el_5),this.parentInjector.get(import21.NgZone),this.renderer,this.parentInjector.get(import22.ComponentFactoryResolver),compView_5.ref,this.parentInjector.get(import23.GestureController),this.parentInjector.get(import24.TransitionController),this.parentInjector.get(import19.DeepLinker,(null as any)));
    this._appEl_5.initComponent(this._Tab_5_4.context,([] as any[]),compView_5);
    compView_5.create(this._Tab_5_4.context,([] as any[]),(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'ion-tab',(null as any));
    this.renderer.setElementAttribute(this._el_7,'role','tabpanel');
    this.renderer.setElementAttribute(this._el_7,'tabIcon','text');
    this.renderer.setElementAttribute(this._el_7,'tabTitle','Message');
    this._appEl_7 = new import3.AppElement(7,3,this,this._el_7);
    var compView_7:any = import13.viewFactory_Tab0(this.viewUtils,this.injector(7),this._appEl_7);
    this._Tab_7_4 = new import13.Wrapper_Tab(this._Tabs_3_4.context,this.parentInjector.get(import17.App),this.parentInjector.get(import14.Config),this.parentInjector.get(import20.Keyboard),new import15.ElementRef(this._el_7),this.parentInjector.get(import21.NgZone),this.renderer,this.parentInjector.get(import22.ComponentFactoryResolver),compView_7.ref,this.parentInjector.get(import23.GestureController),this.parentInjector.get(import24.TransitionController),this.parentInjector.get(import19.DeepLinker,(null as any)));
    this._appEl_7.initComponent(this._Tab_7_4.context,([] as any[]),compView_7);
    compView_7.create(this._Tab_7_4.context,([] as any[]),(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-tab',(null as any));
    this.renderer.setElementAttribute(this._el_9,'role','tabpanel');
    this.renderer.setElementAttribute(this._el_9,'tabIcon','stats');
    this.renderer.setElementAttribute(this._el_9,'tabTitle','Notification');
    this._appEl_9 = new import3.AppElement(9,3,this,this._el_9);
    var compView_9:any = import13.viewFactory_Tab0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Tab_9_4 = new import13.Wrapper_Tab(this._Tabs_3_4.context,this.parentInjector.get(import17.App),this.parentInjector.get(import14.Config),this.parentInjector.get(import20.Keyboard),new import15.ElementRef(this._el_9),this.parentInjector.get(import21.NgZone),this.renderer,this.parentInjector.get(import22.ComponentFactoryResolver),compView_9.ref,this.parentInjector.get(import23.GestureController),this.parentInjector.get(import24.TransitionController),this.parentInjector.get(import19.DeepLinker,(null as any)));
    this._appEl_9.initComponent(this._Tab_9_4.context,([] as any[]),compView_9);
    compView_9.create(this._Tab_9_4.context,([] as any[]),(null as any));
    this._text_10 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'ion-tab',(null as any));
    this.renderer.setElementAttribute(this._el_11,'role','tabpanel');
    this.renderer.setElementAttribute(this._el_11,'tabIcon','image');
    this.renderer.setElementAttribute(this._el_11,'tabTitle','Me');
    this._appEl_11 = new import3.AppElement(11,3,this,this._el_11);
    var compView_11:any = import13.viewFactory_Tab0(this.viewUtils,this.injector(11),this._appEl_11);
    this._Tab_11_4 = new import13.Wrapper_Tab(this._Tabs_3_4.context,this.parentInjector.get(import17.App),this.parentInjector.get(import14.Config),this.parentInjector.get(import20.Keyboard),new import15.ElementRef(this._el_11),this.parentInjector.get(import21.NgZone),this.renderer,this.parentInjector.get(import22.ComponentFactoryResolver),compView_11.ref,this.parentInjector.get(import23.GestureController),this.parentInjector.get(import24.TransitionController),this.parentInjector.get(import19.DeepLinker,(null as any)));
    this._appEl_11.initComponent(this._Tab_11_4.context,([] as any[]),compView_11);
    compView_11.create(this._Tab_11_4.context,([] as any[]),(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n',(null as any));
      compView_3.create(this._Tabs_3_4.context,[([] as any[]).concat([
        this._text_4,
        this._el_5,
        this._text_6,
        this._el_7,
        this._text_8,
        this._el_9,
        this._text_10,
        this._el_11,
        this._text_12
      ]
    )],(null as any));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import25.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Header_0_3.context; }
    if (((token === import26.Tab) && (5 === requestNodeIndex))) { return this._Tab_5_4.context; }
    if (((token === import26.Tab) && (7 === requestNodeIndex))) { return this._Tab_7_4.context; }
    if (((token === import26.Tab) && (9 === requestNodeIndex))) { return this._Tab_9_4.context; }
    if (((token === import26.Tab) && (11 === requestNodeIndex))) { return this._Tab_11_4.context; }
    if (((token === import27.Tabs) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Tabs_3_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Tabs_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    const currVal_0:any = this.context.tab1Root;
    this._Tab_5_4.check_root(currVal_0,throwOnChange,false);
    const currVal_1:any = 'My Services';
    this._Tab_5_4.check_tabTitle(currVal_1,throwOnChange,false);
    const currVal_2:any = 'home';
    this._Tab_5_4.check_tabIcon(currVal_2,throwOnChange,false);
    this._Tab_5_4.detectChangesInternal(this,this._el_5,throwOnChange);
    const currVal_5:any = this.context.tab2Root;
    this._Tab_7_4.check_root(currVal_5,throwOnChange,false);
    const currVal_6:any = 'Message';
    this._Tab_7_4.check_tabTitle(currVal_6,throwOnChange,false);
    const currVal_7:any = 'text';
    this._Tab_7_4.check_tabIcon(currVal_7,throwOnChange,false);
    this._Tab_7_4.detectChangesInternal(this,this._el_7,throwOnChange);
    const currVal_10:any = this.context.tab3Root;
    this._Tab_9_4.check_root(currVal_10,throwOnChange,false);
    const currVal_11:any = 'Notification';
    this._Tab_9_4.check_tabTitle(currVal_11,throwOnChange,false);
    const currVal_12:any = 'stats';
    this._Tab_9_4.check_tabIcon(currVal_12,throwOnChange,false);
    this._Tab_9_4.detectChangesInternal(this,this._el_9,throwOnChange);
    const currVal_15:any = this.context.tab4Root;
    this._Tab_11_4.check_root(currVal_15,throwOnChange,false);
    const currVal_16:any = 'Me';
    this._Tab_11_4.check_tabTitle(currVal_16,throwOnChange,false);
    const currVal_17:any = 'image';
    this._Tab_11_4.check_tabIcon(currVal_17,throwOnChange,false);
    this._Tab_11_4.detectChangesInternal(this,this._el_11,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = this._Tab_5_4.context._tabId;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementAttribute(this._el_5,'id',((currVal_3 == (null as any))? (null as any): currVal_3.toString()));
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._Tab_5_4.context._btnId;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementAttribute(this._el_5,'aria-labelledby',((currVal_4 == (null as any))? (null as any): currVal_4.toString()));
      this._expr_4 = currVal_4;
    }
    const currVal_8:any = this._Tab_7_4.context._tabId;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementAttribute(this._el_7,'id',((currVal_8 == (null as any))? (null as any): currVal_8.toString()));
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._Tab_7_4.context._btnId;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementAttribute(this._el_7,'aria-labelledby',((currVal_9 == (null as any))? (null as any): currVal_9.toString()));
      this._expr_9 = currVal_9;
    }
    const currVal_13:any = this._Tab_9_4.context._tabId;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementAttribute(this._el_9,'id',((currVal_13 == (null as any))? (null as any): currVal_13.toString()));
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._Tab_9_4.context._btnId;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementAttribute(this._el_9,'aria-labelledby',((currVal_14 == (null as any))? (null as any): currVal_14.toString()));
      this._expr_14 = currVal_14;
    }
    const currVal_18:any = this._Tab_11_4.context._tabId;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementAttribute(this._el_11,'id',((currVal_18 == (null as any))? (null as any): currVal_18.toString()));
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._Tab_11_4.context._btnId;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementAttribute(this._el_11,'aria-labelledby',((currVal_19 == (null as any))? (null as any): currVal_19.toString()));
      this._expr_19 = currVal_19;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Tabs_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Tabs_3_4.context.ngOnDestroy();
  }
}
export function viewFactory_HomePage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.HomePage> {
  if ((renderType_HomePage === (null as any))) { (renderType_HomePage = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_HomePage,{})); }
  return new _View_HomePage0(viewUtils,parentInjector,declarationEl);
}