/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './my-services';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../providers/data/data.service';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import14 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import15 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/segment/segment.ngfactory';
import * as import17 from '@angular/core/src/linker/query_list';
import * as import18 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/searchbar/searchbar.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import23 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import24 from 'ionic-angular/config/config';
import * as import25 from '@angular/core/src/linker/element_ref';
import * as import26 from 'ionic-angular/navigation/view-controller';
import * as import27 from 'ionic-angular/components/app/app';
import * as import28 from 'ionic-angular/components/toolbar/toolbar';
import * as import29 from '@angular/forms/src/directives/ng_control';
import * as import30 from 'ionic-angular/util/keyboard';
import * as import31 from '@angular/core/src/zone/ng_zone';
import * as import32 from 'ionic-angular/components/tabs/tabs';
import * as import33 from '@angular/core/src/linker/template_ref';
import * as import34 from 'ionic-angular/components/segment/segment';
import * as import35 from '@angular/forms/src/directives/ng_model';
import * as import36 from '@angular/forms/src/directives/ng_control_status';
import * as import37 from 'ionic-angular/components/icon/icon';
import * as import38 from 'ionic-angular/components/button/button';
import * as import39 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import40 from 'ionic-angular/components/navbar/navbar';
import * as import41 from 'ionic-angular/components/searchbar/searchbar';
import * as import42 from '@angular/common/src/directives/ng_if';
import * as import43 from 'ionic-angular/components/content/content';
import * as import44 from '../../node_modules/ionic-angular/components/card/card.ngfactory';
import * as import45 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import46 from '../../node_modules/ionic-angular/components/list/list-header.ngfactory';
import * as import47 from 'ionic-angular/util/form';
import * as import48 from 'ionic-angular/components/item/item-reorder';
import * as import49 from 'ionic-angular/components/item/item';
import * as import50 from 'ionic-angular/components/list/list-header';
import * as import51 from 'ionic-angular/components/card/card';
import * as import52 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import53 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import54 from '@angular/common/src/pipes/async_pipe';
import * as import55 from 'ionic-angular/gestures/gesture-controller';
import * as import56 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import57 from '@angular/common/src/directives/ng_for';
import * as import58 from 'ionic-angular/components/list/list';
import * as import59 from '../../node_modules/ionic-angular/components/grid/grid.ngfactory';
import * as import60 from 'ionic-angular/components/grid/grid';
export class Wrapper_MyServicesPage {
  context:import0.MyServicesPage;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.MyServicesPage(p0,p1);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_MyServicesPage_Host:import2.RenderComponentType = (null as any);
class _View_MyServicesPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _MyServicesPage_0_4:Wrapper_MyServicesPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MyServicesPage_Host0,renderType_MyServicesPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-my-services',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_MyServicesPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._MyServicesPage_0_4 = new Wrapper_MyServicesPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.DataService));
    this._appEl_0.initComponent(this._MyServicesPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._MyServicesPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.MyServicesPage) && (0 === requestNodeIndex))) { return this._MyServicesPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MyServicesPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_MyServicesPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_MyServicesPage_Host === (null as any))) { (renderType_MyServicesPage_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_MyServicesPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const MyServicesPageNgFactory:import11.ComponentFactory<import0.MyServicesPage> = new import11.ComponentFactory<import0.MyServicesPage>('page-my-services',viewFactory_MyServicesPage_Host0,import0.MyServicesPage);
const styles_MyServicesPage:any[] = ([] as any[]);
var renderType_MyServicesPage:import2.RenderComponentType = (null as any);
class _View_MyServicesPage0 extends import1.AppView<import0.MyServicesPage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import12.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import13.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  _NgModel_5_3:import14.Wrapper_NgModel;
  _NgControl_5_4:any;
  _NgControlStatus_5_5:import15.Wrapper_NgControlStatus;
  _Segment_5_6:import16.Wrapper_Segment;
  _query_SegmentButton_5_0:import17.QueryList<any>;
  _text_6:any;
  _el_7:any;
  /*private*/ _appEl_7:import3.AppElement;
  _SegmentButton_7_4:import16.Wrapper_SegmentButton;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import3.AppElement;
  _SegmentButton_10_4:import16.Wrapper_SegmentButton;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _ToolbarItem_14_3:import18.Wrapper_ToolbarItem;
  _query_Button_14_0:import17.QueryList<any>;
  _text_15:any;
  _el_16:any;
  /*private*/ _appEl_16:import3.AppElement;
  _Button_16_4:import19.Wrapper_Button;
  _text_17:any;
  _el_18:any;
  _Icon_18_3:import20.Wrapper_Icon;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import3.AppElement;
  _Toolbar_23_4:import12.Wrapper_Toolbar;
  _text_24:any;
  _el_25:any;
  /*private*/ _appEl_25:import3.AppElement;
  _Searchbar_25_4:import21.Wrapper_Searchbar;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  /*private*/ _appEl_30:import3.AppElement;
  _Content_30_4:import22.Wrapper_Content;
  _text_31:any;
  _anchor_32:any;
  /*private*/ _appEl_32:import3.AppElement;
  _TemplateRef_32_5:any;
  _NgIf_32_6:import23.Wrapper_NgIf;
  _text_33:any;
  _anchor_34:any;
  /*private*/ _appEl_34:import3.AppElement;
  _TemplateRef_34_5:any;
  _NgIf_34_6:import23.Wrapper_NgIf;
  _text_35:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MyServicesPage0,renderType_MyServicesPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import12.Wrapper_Header(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import26.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this.renderer.setElementAttribute(this._el_3,'no-border-bottom','');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import13.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import13.Wrapper_Navbar(this.parentInjector.get(import27.App),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-segment',(null as any));
    this._NgModel_5_3 = new import14.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_5_4 = this._NgModel_5_3.context;
    this._NgControlStatus_5_5 = new import15.Wrapper_NgControlStatus(this._NgControl_5_4);
    this._Segment_5_6 = new import16.Wrapper_Segment(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_5),this.renderer,this._NgControl_5_4);
    this._query_SegmentButton_5_0 = new import17.QueryList<any>();
    this._text_6 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'ion-segment-button',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','segment-button');
    this.renderer.setElementAttribute(this._el_7,'role','button');
    this.renderer.setElementAttribute(this._el_7,'tappable','');
    this.renderer.setElementAttribute(this._el_7,'value','all');
    this._appEl_7 = new import3.AppElement(7,5,this,this._el_7);
    var compView_7:any = import16.viewFactory_SegmentButton0(this.viewUtils,this.injector(7),this._appEl_7);
    this._SegmentButton_7_4 = new import16.Wrapper_SegmentButton(this.renderer,new import25.ElementRef(this._el_7));
    this._appEl_7.initComponent(this._SegmentButton_7_4.context,([] as any[]),compView_7);
    this._text_8 = this.renderer.createText((null as any),'\n                All\n            ',(null as any));
    compView_7.create(this._SegmentButton_7_4.context,[([] as any[]).concat([this._text_8])],(null as any));
    this._text_9 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_5,'ion-segment-button',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','segment-button');
    this.renderer.setElementAttribute(this._el_10,'role','button');
    this.renderer.setElementAttribute(this._el_10,'tappable','');
    this.renderer.setElementAttribute(this._el_10,'value','favorites');
    this._appEl_10 = new import3.AppElement(10,5,this,this._el_10);
    var compView_10:any = import16.viewFactory_SegmentButton0(this.viewUtils,this.injector(10),this._appEl_10);
    this._SegmentButton_10_4 = new import16.Wrapper_SegmentButton(this.renderer,new import25.ElementRef(this._el_10));
    this._appEl_10.initComponent(this._SegmentButton_10_4.context,([] as any[]),compView_10);
    this._text_11 = this.renderer.createText((null as any),'\n                Favorites\n            ',(null as any));
    compView_10.create(this._SegmentButton_10_4.context,[([] as any[]).concat([this._text_11])],(null as any));
    this._text_12 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_14,'end','');
    this._ToolbarItem_14_3 = new import18.Wrapper_ToolbarItem(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import28.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._query_Button_14_0 = new import17.QueryList<any>();
    this._text_15 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'button',(null as any));
    this.renderer.setElementAttribute(this._el_16,'icon-only','');
    this.renderer.setElementAttribute(this._el_16,'ion-button','');
    this.renderer.setElementAttribute(this._el_16,'round','');
    this._appEl_16 = new import3.AppElement(16,14,this,this._el_16);
    var compView_16:any = import19.viewFactory_Button0(this.viewUtils,this.injector(16),this._appEl_16);
    this._Button_16_4 = new import19.Wrapper_Button((null as any),'',this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_16),this.renderer);
    this._appEl_16.initComponent(this._Button_16_4.context,([] as any[]),compView_16);
    this._text_17 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_18 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_18,'name','add');
    this.renderer.setElementAttribute(this._el_18,'role','img');
    this._Icon_18_3 = new import20.Wrapper_Icon(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_18),this.renderer);
    this._text_19 = this.renderer.createText((null as any),'\n            ',(null as any));
      compView_16.create(this._Button_16_4.context,[([] as any[]).concat([
        this._text_17,
        this._el_18,
        this._text_19
      ]
    )],(null as any));
    this._text_20 = this.renderer.createText(this._el_14,'\n        ',(null as any));
    this._text_21 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._el_14]),
      ([] as any[]).concat([
        this._text_4,
        this._el_5,
        this._text_13,
        this._text_21
      ]
      )
    ]
    ,(null as any));
    this._text_22 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_1,'ion-toolbar',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','toolbar');
    this.renderer.setElementAttribute(this._el_23,'no-border-top','');
    this._appEl_23 = new import3.AppElement(23,1,this,this._el_23);
    var compView_23:any = import12.viewFactory_Toolbar0(this.viewUtils,this.injector(23),this._appEl_23);
    this._Toolbar_23_4 = new import12.Wrapper_Toolbar(this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_23),this.renderer);
    this._appEl_23.initComponent(this._Toolbar_23_4.context,([] as any[]),compView_23);
    this._text_24 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_25 = this.renderer.createElement((null as any),'ion-searchbar',(null as any));
    this._appEl_25 = new import3.AppElement(25,23,this,this._el_25);
    var compView_25:any = import21.viewFactory_Searchbar0(this.viewUtils,this.injector(25),this._appEl_25);
    this._Searchbar_25_4 = new import21.Wrapper_Searchbar(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_25),this.renderer,this.parentInjector.get(import29.NgControl,(null as any)));
    this._appEl_25.initComponent(this._Searchbar_25_4.context,([] as any[]),compView_25);
    this._text_26 = this.renderer.createText((null as any),'\n        ',(null as any));
    compView_25.create(this._Searchbar_25_4.context,([] as any[]),(null as any));
    this._text_27 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_23.create(this._Toolbar_23_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_24,
        this._el_25,
        this._text_27
      ]
      )
    ]
    ,(null as any));
    this._text_28 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._text_29 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_30 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_30,'padding','');
    this._appEl_30 = new import3.AppElement(30,(null as any),this,this._el_30);
    var compView_30:any = import22.viewFactory_Content0(this.viewUtils,this.injector(30),this._appEl_30);
    this._Content_30_4 = new import22.Wrapper_Content(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_30),this.renderer,this.parentInjector.get(import27.App),this.parentInjector.get(import30.Keyboard),this.parentInjector.get(import31.NgZone),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import32.Tabs,(null as any)));
    this._appEl_30.initComponent(this._Content_30_4.context,([] as any[]),compView_30);
    this._text_31 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._anchor_32 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_32 = new import3.AppElement(32,30,this,this._anchor_32);
    this._TemplateRef_32_5 = new import33.TemplateRef_(this._appEl_32,viewFactory_MyServicesPage1);
    this._NgIf_32_6 = new import23.Wrapper_NgIf(this._appEl_32.vcRef,this._TemplateRef_32_5);
    this._text_33 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._anchor_34 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_34 = new import3.AppElement(34,30,this,this._anchor_34);
    this._TemplateRef_34_5 = new import33.TemplateRef_(this._appEl_34,viewFactory_MyServicesPage2);
    this._NgIf_34_6 = new import23.Wrapper_NgIf(this._appEl_34.vcRef,this._TemplateRef_34_5);
    this._text_35 = this.renderer.createText((null as any),'\n',(null as any));
    compView_30.create(this._Content_30_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_31,
        this._appEl_32,
        this._text_33,
        this._appEl_34,
        this._text_35
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_5,'ngModelChange',this.eventHandler(this._handle_ngModelChange_5_0.bind(this)));
    const subscription_0:any = this._NgModel_5_3.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_5_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_7,'click',this.eventHandler(this._handle_click_7_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_10,'click',this.eventHandler(this._handle_click_10_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_16,'click',this.eventHandler(this._handle_click_16_0.bind(this)));
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_25,'ionInput',this.eventHandler(this._handle_ionInput_25_0.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_25,'ionCancel',this.eventHandler(this._handle_ionCancel_25_1.bind(this)));
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    const subscription_1:any = this._Searchbar_25_4.context.ionInput.subscribe(this.eventHandler(this._handle_ionInput_25_0.bind(this)));
    const subscription_2:any = this._Searchbar_25_4.context.ionCancel.subscribe(this.eventHandler(this._handle_ionCancel_25_1.bind(this)));
    this._expr_29 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._anchor_32,
      this._text_33,
      this._anchor_34,
      this._text_35
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import34.SegmentButton) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._SegmentButton_7_4.context; }
    if (((token === import34.SegmentButton) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._SegmentButton_10_4.context; }
    if (((token === import35.NgModel) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._NgModel_5_3.context; }
    if (((token === import29.NgControl) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._NgControl_5_4; }
    if (((token === import36.NgControlStatus) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._NgControlStatus_5_5.context; }
    if (((token === import34.Segment) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Segment_5_6.context; }
    if (((token === import37.Icon) && (18 === requestNodeIndex))) { return this._Icon_18_3.context; }
    if (((token === import38.Button) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._Button_16_4.context; }
    if (((token === import39.ToolbarItem) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._ToolbarItem_14_3.context; }
    if (((token === import40.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Navbar_3_4.context; }
    if (((token === import41.Searchbar) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Searchbar_25_4.context; }
    if (((token === import28.Toolbar) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Toolbar_23_4.context; }
    if (((token === import28.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Header_1_3.context; }
    if (((token === import33.TemplateRef) && (32 === requestNodeIndex))) { return this._TemplateRef_32_5; }
    if (((token === import42.NgIf) && (32 === requestNodeIndex))) { return this._NgIf_32_6.context; }
    if (((token === import33.TemplateRef) && (34 === requestNodeIndex))) { return this._TemplateRef_34_5; }
    if (((token === import42.NgIf) && (34 === requestNodeIndex))) { return this._NgIf_34_6.context; }
    if (((token === import43.Content) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._Content_30_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    const currVal_3:any = this.context.segment;
    this._NgModel_5_3.check_model(currVal_3,throwOnChange,false);
    this._NgModel_5_3.detectChangesInternal(this,this._el_5,throwOnChange);
    this._NgControlStatus_5_5.detectChangesInternal(this,this._el_5,throwOnChange);
    this._Segment_5_6.detectChangesInternal(this,this._el_5,throwOnChange);
    const currVal_12:any = 'all';
    this._SegmentButton_7_4.check_value(currVal_12,throwOnChange,false);
    this._SegmentButton_7_4.detectChangesInternal(this,this._el_7,throwOnChange);
    const currVal_15:any = 'favorites';
    this._SegmentButton_10_4.check_value(currVal_15,throwOnChange,false);
    this._SegmentButton_10_4.detectChangesInternal(this,this._el_10,throwOnChange);
    this._ToolbarItem_14_3.detectChangesInternal(this,this._el_14,throwOnChange);
    const currVal_17:any = '';
    this._Button_16_4.check_round(currVal_17,throwOnChange,false);
    if (this._Button_16_4.detectChangesInternal(this,this._el_16,throwOnChange)) { this._appEl_16.componentView.markAsCheckOnce(); }
    const currVal_18:any = 'add';
    this._Icon_18_3.check_name(currVal_18,throwOnChange,false);
    this._Icon_18_3.detectChangesInternal(this,this._el_18,throwOnChange);
    if (this._Toolbar_23_4.detectChangesInternal(this,this._el_23,throwOnChange)) { this._appEl_23.componentView.markAsCheckOnce(); }
    this._Searchbar_25_4.detectChangesInternal(this,this._el_25,throwOnChange);
    if (this._Content_30_4.detectChangesInternal(this,this._el_30,throwOnChange)) { this._appEl_30.componentView.markAsCheckOnce(); }
    const currVal_30:boolean = !this.context.allServiceList;
    this._NgIf_32_6.check_ngIf(currVal_30,throwOnChange,false);
    this._NgIf_32_6.detectChangesInternal(this,this._anchor_32,throwOnChange);
    const currVal_31:any = this.context.resultsList;
    this._NgIf_34_6.check_ngIf(currVal_31,throwOnChange,false);
    this._NgIf_34_6.detectChangesInternal(this,this._anchor_34,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_SegmentButton_5_0.dirty) {
        this._query_SegmentButton_5_0.reset([
          this._SegmentButton_7_4.context,
          this._SegmentButton_10_4.context
        ]
        );
        this._Segment_5_6.context._buttons = this._query_SegmentButton_5_0;
        this._query_SegmentButton_5_0.notifyOnChanges();
      }
      if (this._query_Button_14_0.dirty) {
        this._query_Button_14_0.reset([this._Button_16_4.context]);
        this._ToolbarItem_14_3.context._buttons = this._query_Button_14_0;
        this._query_Button_14_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_16_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Searchbar_25_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_3_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_3_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._NgControlStatus_5_5.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_5,'ng-untouched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatus_5_5.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_5,'ng-touched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatus_5_5.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_5,'ng-pristine',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatus_5_5.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_5,'ng-dirty',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_5_5.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_5,'ng-valid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_5_5.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_5,'ng-invalid',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_19:any = this._Icon_18_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_18,'hide',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._Toolbar_23_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_23,'statusbar-padding',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_23:any = this._Searchbar_25_4.context.animated;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_25,'searchbar-animated',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._Searchbar_25_4.context._value;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_25,'searchbar-has-value',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = this._Searchbar_25_4.context._isActive;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_25,'searchbar-active',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._Searchbar_25_4.context.showCancelButton;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_25,'searchbar-show-cancel',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._Searchbar_25_4.context._shouldAlignLeft;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_25,'searchbar-left-aligned',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._Searchbar_25_4.context._sbHasFocus;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_25,'searchbar-has-focus',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._Content_30_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_30,'statusbar-padding',currVal_29);
      this._expr_29 = currVal_29;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Segment_5_6.context.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); }
    }
  }
  destroyInternal():void {
    this._NgModel_5_3.context.ngOnDestroy();
    this._Icon_18_3.context.ngOnDestroy();
    this._Content_30_4.context.ngOnDestroy();
  }
  private _handle_ngModelChange_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.segment = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_7_0($event:any):boolean {
    this._appEl_7.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onChangeSegment('all')) !== false);
    const pd_1:any = ((<any>this._SegmentButton_7_4.context.onClick()) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_click_10_0($event:any):boolean {
    this._appEl_10.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onChangeSegment('favorites')) !== false);
    const pd_1:any = ((<any>this._SegmentButton_10_4.context.onClick()) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_click_16_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.newService()) !== false);
    return (true && pd_0);
  }
  private _handle_ionInput_25_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onInput($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionCancel_25_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onCancel($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_MyServicesPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.MyServicesPage> {
  if ((renderType_MyServicesPage === (null as any))) { (renderType_MyServicesPage = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_MyServicesPage,{})); }
  return new _View_MyServicesPage0(viewUtils,parentInjector,declarationEl);
}
class _View_MyServicesPage1 extends import1.AppView<any> {
  _el_0:any;
  _Card_0_3:import44.Wrapper_Card;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Item_2_4:import45.Wrapper_Item;
  _ListHeader_2_5:import46.Wrapper_ListHeader;
  _query_Label_2_0:import17.QueryList<any>;
  _query_Button_2_1:import17.QueryList<any>;
  _query_Icon_2_2:import17.QueryList<any>;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _CardContent_5_3:import44.Wrapper_CardContent;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MyServicesPage1,renderType_MyServicesPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_0_3 = new import44.Wrapper_Card(this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','my-team-header item');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import45.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import45.Wrapper_Item(this.parent.parentInjector.get(import47.Form),this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_2),this.renderer,this.parent.parentInjector.get(import48.ItemReorder,(null as any)));
    this._ListHeader_2_5 = new import46.Wrapper_ListHeader(this.parent.parentInjector.get(import24.Config),this.renderer,new import25.ElementRef(this._el_2),(null as any));
    this._query_Label_2_0 = new import17.QueryList<any>();
    this._query_Button_2_1 = new import17.QueryList<any>();
    this._query_Icon_2_2 = new import17.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'No Joined Services.',(null as any));
    this._query_Label_2_0.reset(([] as any[]));
    this._Item_2_4.context.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_3]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'ion-card-content',(null as any));
    this._CardContent_5_3 = new import44.Wrapper_CardContent(this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_5),this.renderer);
    this._text_6 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'p',(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'You are not currently joining any servcices.',(null as any));
    this._text_9 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_5,'p',(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'Adding a service by clicking the \'+\' icon at the right top corner.',(null as any));
    this._text_12 = this.renderer.createText(this._el_5,'\n\n        ',(null as any));
    this._text_13 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import49.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Item_2_4.context; }
    if (((token === import50.ListHeader) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._ListHeader_2_5.context; }
    if (((token === import51.CardContent) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._CardContent_5_3.context; }
    if (((token === import51.Card) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Card_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Card_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    if (this._Item_2_4.detectChangesInternal(this,this._el_2,throwOnChange)) { this._appEl_2.componentView.markAsCheckOnce(); }
    this._ListHeader_2_5.detectChangesInternal(this,this._el_2,throwOnChange);
    this._CardContent_5_3.detectChangesInternal(this,this._el_5,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset(([] as any[]));
        this._Item_2_4.context._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset(([] as any[]));
        this._Item_2_4.context._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.context.ngAfterContentInit(); }
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_MyServicesPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_MyServicesPage1(viewUtils,parentInjector,declarationEl);
}
class _View_MyServicesPage2 extends import1.AppView<any> {
  _el_0:any;
  _List_0_3:import52.Wrapper_List;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import53.Wrapper_NgFor;
  _text_3:any;
  _pipe_async_0:import54.AsyncPipe;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MyServicesPage2,renderType_MyServicesPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_0,'no-border','');
    this._List_0_3 = new import52.Wrapper_List(this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_0),this.renderer,this.parent.parentInjector.get(import55.GestureController));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import3.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import33.TemplateRef_(this._appEl_2,viewFactory_MyServicesPage3);
    this._NgFor_2_6 = new import53.Wrapper_NgFor(this._appEl_2.vcRef,this._TemplateRef_2_5,this.parent.parentInjector.get(import56.IterableDiffers),this.parent.ref);
    this._text_3 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._pipe_async_0 = new import54.AsyncPipe(this.parent.ref);
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import33.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import57.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6.context; }
    if (((token === import58.List) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._List_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    this._List_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    valUnwrapper.reset();
    const currVal_0:any = valUnwrapper.unwrap(this._pipe_async_0.transform(this.parent.context.resultsList));
    this._NgFor_2_6.check_ngForOf(currVal_0,throwOnChange,valUnwrapper.hasWrappedValue);
    this._NgFor_2_6.detectChangesInternal(this,this._anchor_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._pipe_async_0.ngOnDestroy();
  }
}
function viewFactory_MyServicesPage2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_MyServicesPage2(viewUtils,parentInjector,declarationEl);
}
class _View_MyServicesPage3 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import45.Wrapper_Item;
  _ItemContent_0_5:import45.Wrapper_ItemContent;
  _query_Label_0_0:import17.QueryList<any>;
  _query_Button_0_1:import17.QueryList<any>;
  _query_Icon_0_2:import17.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Row_2_3:import59.Wrapper_Row;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import23.Wrapper_NgIf;
  _text_5:any;
  _text_6:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MyServicesPage3,renderType_MyServicesPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import45.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import45.Wrapper_Item(this.parent.parent.parentInjector.get(import47.Form),this.parent.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_0),this.renderer,this.parent.parent.parentInjector.get(import48.ItemReorder,(null as any)));
    this._ItemContent_0_5 = new import45.Wrapper_ItemContent();
    this._query_Label_0_0 = new import17.QueryList<any>();
    this._query_Button_0_1 = new import17.QueryList<any>();
    this._query_Icon_0_2 = new import17.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this._Row_2_3 = new import59.Wrapper_Row();
    this._text_3 = this.renderer.createText(this._el_2,'\n                ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_4 = new import3.AppElement(4,2,this,this._anchor_4);
    this._TemplateRef_4_5 = new import33.TemplateRef_(this._appEl_4,viewFactory_MyServicesPage4);
    this._NgIf_4_6 = new import23.Wrapper_NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._el_2,
        this._text_6
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._text_6
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import33.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import42.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6.context; }
    if (((token === import60.Row) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._Row_2_3.context; }
    if (((token === import49.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Item_0_4.context; }
    if (((token === import49.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ItemContent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Row_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    const currVal_0:any = this.context.$implicit.dtl;
    this._NgIf_4_6.check_ngIf(currVal_0,throwOnChange,false);
    this._NgIf_4_6.detectChangesInternal(this,this._anchor_4,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_MyServicesPage3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_MyServicesPage3(viewUtils,parentInjector,declarationEl);
}
class _View_MyServicesPage4 extends import1.AppView<any> {
  _el_0:any;
  _Card_0_3:import44.Wrapper_Card;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _CardContent_4_3:import44.Wrapper_CardContent;
  _text_5:any;
  _el_6:any;
  _CardTitle_6_3:import44.Wrapper_CardTitle;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _Row_13_3:import59.Wrapper_Row;
  _text_14:any;
  _el_15:any;
  _Col_15_3:import59.Wrapper_Col;
  _text_16:any;
  _el_17:any;
  /*private*/ _appEl_17:import3.AppElement;
  _Button_17_4:import19.Wrapper_Button;
  _text_18:any;
  _el_19:any;
  _Icon_19_3:import20.Wrapper_Icon;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MyServicesPage4,renderType_MyServicesPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_0_3 = new import44.Wrapper_Card(this.parent.parent.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n\n                    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'img',(null as any));
    this.renderer.setElementAttribute(this._el_2,'alt','Service Logo');
    this.renderer.setElementAttribute(this._el_2,'src','../assets/img/avatars.png');
    this.renderer.setElementAttribute(this._el_2,'width-33','');
    this._text_3 = this.renderer.createText(this._el_0,'\n\n                    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_0,'ion-card-content',(null as any));
    this._CardContent_4_3 = new import44.Wrapper_CardContent(this.parent.parent.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_4),this.renderer);
    this._text_5 = this.renderer.createText(this._el_4,'\n\n                        ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'ion-card-title',(null as any));
    this._CardTitle_6_3 = new import44.Wrapper_CardTitle(this.parent.parent.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n                        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_4,'p',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n                    ',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_0,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_13,'color','primary');
    this.renderer.setElementAttribute(this._el_13,'no-padding','');
    this._Row_13_3 = new import59.Wrapper_Row();
    this._text_14 = this.renderer.createText(this._el_13,'\n                        ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'ion-col',(null as any));
    this._Col_15_3 = new import59.Wrapper_Col();
    this._text_16 = this.renderer.createText(this._el_15,'\n                            ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'button',(null as any));
    this.renderer.setElementAttribute(this._el_17,'clear','');
    this.renderer.setElementAttribute(this._el_17,'color','danger');
    this.renderer.setElementAttribute(this._el_17,'icon-left','');
    this.renderer.setElementAttribute(this._el_17,'ion-button','');
    this.renderer.setElementAttribute(this._el_17,'small','');
    this._appEl_17 = new import3.AppElement(17,15,this,this._el_17);
    var compView_17:any = import19.viewFactory_Button0(this.viewUtils,this.injector(17),this._appEl_17);
    this._Button_17_4 = new import19.Wrapper_Button((null as any),'',this.parent.parent.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_17),this.renderer);
    this._appEl_17.initComponent(this._Button_17_4.context,([] as any[]),compView_17);
    this._text_18 = this.renderer.createText((null as any),'\n                                ',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_19,'name','calendar');
    this.renderer.setElementAttribute(this._el_19,'role','img');
    this._Icon_19_3 = new import20.Wrapper_Icon(this.parent.parent.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_19),this.renderer);
    this._text_20 = this.renderer.createText((null as any),'',(null as any));
      compView_17.create(this._Button_17_4.context,[([] as any[]).concat([
        this._text_18,
        this._el_19,
        this._text_20
      ]
    )],(null as any));
    this._text_21 = this.renderer.createText(this._el_15,'\n                        ',(null as any));
    this._text_22 = this.renderer.createText(this._el_13,'\n\n                    ',(null as any));
    this._text_23 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._text_23
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import51.CardTitle) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._CardTitle_6_3.context; }
    if (((token === import51.CardContent) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._CardContent_4_3.context; }
    if (((token === import37.Icon) && (19 === requestNodeIndex))) { return this._Icon_19_3.context; }
    if (((token === import38.Button) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._Button_17_4.context; }
    if (((token === import60.Col) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Col_15_3.context; }
    if (((token === import60.Row) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Row_13_3.context; }
    if (((token === import51.Card) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Card_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Card_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._CardContent_4_3.detectChangesInternal(this,this._el_4,throwOnChange);
    this._CardTitle_6_3.detectChangesInternal(this,this._el_6,throwOnChange);
    this._Row_13_3.detectChangesInternal(this,this._el_13,throwOnChange);
    this._Col_15_3.detectChangesInternal(this,this._el_15,throwOnChange);
    const currVal_3:any = '';
    this._Button_17_4.check_small(currVal_3,throwOnChange,false);
    const currVal_4:any = '';
    this._Button_17_4.check_clear(currVal_4,throwOnChange,false);
    const currVal_5:any = 'danger';
    this._Button_17_4.check_color(currVal_5,throwOnChange,false);
    if (this._Button_17_4.detectChangesInternal(this,this._el_17,throwOnChange)) { this._appEl_17.componentView.markAsCheckOnce(); }
    const currVal_6:any = 'calendar';
    this._Icon_19_3.check_name(currVal_6,throwOnChange,false);
    this._Icon_19_3.detectChangesInternal(this,this._el_19,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_17_4.context.ngAfterContentInit(); } }
    const currVal_1:any = import4.interpolate(1,'\n                            ',this.parent.context.$implicit.dtl.serviceTitle,'\n                        ');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_7,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'\n                            ',this.parent.context.$implicit.dtl.serviceDesc,'\n                        ');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_10,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_7:any = this._Icon_19_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_19,'hide',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = import4.interpolate(1,'\n                                ',this.parent.context.$implicit.dtl.serviceStartDate,'\n                                ');
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setText(this._text_20,currVal_8);
      this._expr_8 = currVal_8;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_19_3.context.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.parent.context.onCardClick($event,this.parent.context.$implicit.dtl)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_MyServicesPage4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_MyServicesPage4(viewUtils,parentInjector,declarationEl);
}