/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './register';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/forms/src/form_builder';
import * as import10 from '../../providers/users/users.service';
import * as import11 from 'ionic-angular/components/loading/loading';
import * as import12 from 'ionic-angular/components/alert/alert';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import19 from '../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.ngfactory';
import * as import20 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import22 from '@angular/core/src/linker/query_list';
import * as import23 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import24 from '../../node_modules/@angular/forms/src/directives/reactive_directives/form_control_name.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import26 from '../../components/control-message/control-message.ngfactory';
import * as import27 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import28 from 'ionic-angular/config/config';
import * as import29 from '@angular/core/src/linker/element_ref';
import * as import30 from 'ionic-angular/navigation/view-controller';
import * as import31 from 'ionic-angular/components/app/app';
import * as import32 from 'ionic-angular/components/toolbar/toolbar';
import * as import33 from 'ionic-angular/util/keyboard';
import * as import34 from '@angular/core/src/zone/ng_zone';
import * as import35 from 'ionic-angular/components/tabs/tabs';
import * as import36 from 'ionic-angular/util/form';
import * as import37 from 'ionic-angular/components/item/item-reorder';
import * as import38 from 'ionic-angular/platform/platform';
import * as import39 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import40 from 'ionic-angular/components/navbar/navbar';
import * as import41 from 'ionic-angular/components/label/label';
import * as import42 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import43 from '@angular/forms/src/directives/ng_control';
import * as import44 from '@angular/forms/src/directives/ng_control_status';
import * as import45 from 'ionic-angular/components/input/input';
import * as import46 from 'ionic-angular/components/item/item';
import * as import47 from '../../components/control-message/control-message';
import * as import48 from 'ionic-angular/components/button/button';
import * as import49 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import50 from '@angular/forms/src/directives/control_container';
import * as import51 from 'ionic-angular/components/content/content';
export class Wrapper_RegisterPage {
  context:import0.RegisterPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any) {
    this.changed = false;
    this.context = new import0.RegisterPage(p0,p1,p2,p3,p4);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_RegisterPage_Host:import2.RenderComponentType = (null as any);
class _View_RegisterPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _RegisterPage_0_4:Wrapper_RegisterPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_RegisterPage_Host0,renderType_RegisterPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-register',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_RegisterPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._RegisterPage_0_4 = new Wrapper_RegisterPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.FormBuilder),this.parentInjector.get(import10.UsersService),this.parentInjector.get(import11.LoadingController),this.parentInjector.get(import12.AlertController));
    this._appEl_0.initComponent(this._RegisterPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._RegisterPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.RegisterPage) && (0 === requestNodeIndex))) { return this._RegisterPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._RegisterPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_RegisterPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_RegisterPage_Host === (null as any))) { (renderType_RegisterPage_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_RegisterPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const RegisterPageNgFactory:import14.ComponentFactory<import0.RegisterPage> = new import14.ComponentFactory<import0.RegisterPage>('page-register',viewFactory_RegisterPage_Host0,import0.RegisterPage);
const styles_RegisterPage:any[] = ([] as any[]);
var renderType_RegisterPage:import2.RenderComponentType = (null as any);
class _View_RegisterPage0 extends import1.AppView<import0.RegisterPage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import15.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import16.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _ToolbarTitle_5_4:import17.Wrapper_ToolbarTitle;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import3.AppElement;
  _Content_10_4:import18.Wrapper_Content;
  _text_11:any;
  _el_12:any;
  _FormGroupDirective_12_3:import19.Wrapper_FormGroupDirective;
  _ControlContainer_12_4:any;
  _NgControlStatusGroup_12_5:import20.Wrapper_NgControlStatusGroup;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import3.AppElement;
  _Item_14_4:import21.Wrapper_Item;
  _ItemContent_14_5:import21.Wrapper_ItemContent;
  _query_Label_14_0:import22.QueryList<any>;
  _query_Button_14_1:import22.QueryList<any>;
  _query_Icon_14_2:import22.QueryList<any>;
  _text_15:any;
  _el_16:any;
  _Label_16_3:import23.Wrapper_Label;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  /*private*/ _appEl_19:import3.AppElement;
  _FormControlName_19_4:import24.Wrapper_FormControlName;
  _NgControl_19_5:any;
  _NgControlStatus_19_6:import20.Wrapper_NgControlStatus;
  _TextInput_19_7:import25.Wrapper_TextInput;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  /*private*/ _appEl_22:import3.AppElement;
  _ControlMessageComponent_22_4:import26.Wrapper_ControlMessageComponent;
  _text_23:any;
  _el_24:any;
  /*private*/ _appEl_24:import3.AppElement;
  _Item_24_4:import21.Wrapper_Item;
  _ItemContent_24_5:import21.Wrapper_ItemContent;
  _query_Label_24_0:import22.QueryList<any>;
  _query_Button_24_1:import22.QueryList<any>;
  _query_Icon_24_2:import22.QueryList<any>;
  _text_25:any;
  _el_26:any;
  _Label_26_3:import23.Wrapper_Label;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  /*private*/ _appEl_29:import3.AppElement;
  _FormControlName_29_4:import24.Wrapper_FormControlName;
  _NgControl_29_5:any;
  _NgControlStatus_29_6:import20.Wrapper_NgControlStatus;
  _TextInput_29_7:import25.Wrapper_TextInput;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  /*private*/ _appEl_32:import3.AppElement;
  _ControlMessageComponent_32_4:import26.Wrapper_ControlMessageComponent;
  _text_33:any;
  _el_34:any;
  /*private*/ _appEl_34:import3.AppElement;
  _Item_34_4:import21.Wrapper_Item;
  _ItemContent_34_5:import21.Wrapper_ItemContent;
  _query_Label_34_0:import22.QueryList<any>;
  _query_Button_34_1:import22.QueryList<any>;
  _query_Icon_34_2:import22.QueryList<any>;
  _text_35:any;
  _el_36:any;
  _Label_36_3:import23.Wrapper_Label;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  /*private*/ _appEl_39:import3.AppElement;
  _FormControlName_39_4:import24.Wrapper_FormControlName;
  _NgControl_39_5:any;
  _NgControlStatus_39_6:import20.Wrapper_NgControlStatus;
  _TextInput_39_7:import25.Wrapper_TextInput;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  /*private*/ _appEl_42:import3.AppElement;
  _ControlMessageComponent_42_4:import26.Wrapper_ControlMessageComponent;
  _text_43:any;
  _el_44:any;
  /*private*/ _appEl_44:import3.AppElement;
  _Item_44_4:import21.Wrapper_Item;
  _ItemContent_44_5:import21.Wrapper_ItemContent;
  _query_Label_44_0:import22.QueryList<any>;
  _query_Button_44_1:import22.QueryList<any>;
  _query_Icon_44_2:import22.QueryList<any>;
  _text_45:any;
  _el_46:any;
  _Label_46_3:import23.Wrapper_Label;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  /*private*/ _appEl_49:import3.AppElement;
  _FormControlName_49_4:import24.Wrapper_FormControlName;
  _NgControl_49_5:any;
  _NgControlStatus_49_6:import20.Wrapper_NgControlStatus;
  _TextInput_49_7:import25.Wrapper_TextInput;
  _text_50:any;
  _text_51:any;
  _el_52:any;
  /*private*/ _appEl_52:import3.AppElement;
  _ControlMessageComponent_52_4:import26.Wrapper_ControlMessageComponent;
  _text_53:any;
  _el_54:any;
  /*private*/ _appEl_54:import3.AppElement;
  _Button_54_4:import27.Wrapper_Button;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_46:any;
  /*private*/ _expr_47:any;
  /*private*/ _expr_50:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_RegisterPage0,renderType_RegisterPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import15.Wrapper_Header(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import30.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n\n    ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this.renderer.setElementAttribute(this._el_3,'color','primary');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import16.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import16.Wrapper_Navbar(this.parentInjector.get(import31.App),this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_5 = new import3.AppElement(5,3,this,this._el_5);
    var compView_5:any = import17.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(5),this._appEl_5);
    this._ToolbarTitle_5_4 = new import17.Wrapper_ToolbarTitle(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import32.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._appEl_5.initComponent(this._ToolbarTitle_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'Registration',(null as any));
    compView_5.create(this._ToolbarTitle_5_4.context,[([] as any[]).concat([this._text_6])],(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_4,
        this._el_5,
        this._text_7
      ]
      )
    ]
    ,(null as any));
    this._text_8 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_10 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_10,'padding','');
    this._appEl_10 = new import3.AppElement(10,(null as any),this,this._el_10);
    var compView_10:any = import18.viewFactory_Content0(this.viewUtils,this.injector(10),this._appEl_10);
    this._Content_10_4 = new import18.Wrapper_Content(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import31.App),this.parentInjector.get(import33.Keyboard),this.parentInjector.get(import34.NgZone),this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import35.Tabs,(null as any)));
    this._appEl_10.initComponent(this._Content_10_4.context,([] as any[]),compView_10);
    this._text_11 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'form',(null as any));
    this._FormGroupDirective_12_3 = new import19.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_12_4 = this._FormGroupDirective_12_3.context;
    this._NgControlStatusGroup_12_5 = new import20.Wrapper_NgControlStatusGroup(this._ControlContainer_12_4);
    this._text_13 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','item item-block');
    this._appEl_14 = new import3.AppElement(14,12,this,this._el_14);
    var compView_14:any = import21.viewFactory_Item0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Item_14_4 = new import21.Wrapper_Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import37.ItemReorder,(null as any)));
    this._ItemContent_14_5 = new import21.Wrapper_ItemContent();
    this._query_Label_14_0 = new import22.QueryList<any>();
    this._query_Button_14_1 = new import22.QueryList<any>();
    this._query_Icon_14_2 = new import22.QueryList<any>();
    this._appEl_14.initComponent(this._Item_14_4.context,([] as any[]),compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_16,'floating','');
    this._Label_16_3 = new import23.Wrapper_Label(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_16),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'First Name ',(null as any));
    this._text_18 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_19,'formControlName','fname');
    this.renderer.setElementAttribute(this._el_19,'type','text');
    this._appEl_19 = new import3.AppElement(19,14,this,this._el_19);
    var compView_19:any = import25.viewFactory_TextInput0(this.viewUtils,this.injector(19),this._appEl_19);
    this._FormControlName_19_4 = new import24.Wrapper_FormControlName(this._ControlContainer_12_4,(null as any),(null as any),(null as any));
    this._NgControl_19_5 = this._FormControlName_19_4.context;
    this._NgControlStatus_19_6 = new import20.Wrapper_NgControlStatus(this._NgControl_19_5);
    this._TextInput_19_7 = new import25.Wrapper_TextInput(this.parentInjector.get(import28.Config),this.parentInjector.get(import36.Form),this._Item_14_4.context,this.parentInjector.get(import31.App),this.parentInjector.get(import38.Platform),new import29.ElementRef(this._el_19),this.renderer,this._Content_10_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_19_5);
    this._appEl_19.initComponent(this._TextInput_19_7.context,([] as any[]),compView_19);
    compView_19.create(this._TextInput_19_7.context,([] as any[]),(null as any));
    this._text_20 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._query_Label_14_0.reset([this._Label_16_3.context]);
    this._Item_14_4.context.contentLabel = this._query_Label_14_0.first;
    compView_14.create(this._Item_14_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_16]),
      ([] as any[]).concat([
        this._text_15,
        this._text_18,
        this._text_20
      ]
      ),
      ([] as any[]).concat([this._el_19]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_21 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_12,'control-message',(null as any));
    this._appEl_22 = new import3.AppElement(22,12,this,this._el_22);
    var compView_22:any = import26.viewFactory_ControlMessageComponent0(this.viewUtils,this.injector(22),this._appEl_22);
    this._ControlMessageComponent_22_4 = new import26.Wrapper_ControlMessageComponent();
    this._appEl_22.initComponent(this._ControlMessageComponent_22_4.context,([] as any[]),compView_22);
    compView_22.create(this._ControlMessageComponent_22_4.context,([] as any[]),(null as any));
    this._text_23 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','item item-block');
    this._appEl_24 = new import3.AppElement(24,12,this,this._el_24);
    var compView_24:any = import21.viewFactory_Item0(this.viewUtils,this.injector(24),this._appEl_24);
    this._Item_24_4 = new import21.Wrapper_Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_24),this.renderer,this.parentInjector.get(import37.ItemReorder,(null as any)));
    this._ItemContent_24_5 = new import21.Wrapper_ItemContent();
    this._query_Label_24_0 = new import22.QueryList<any>();
    this._query_Button_24_1 = new import22.QueryList<any>();
    this._query_Icon_24_2 = new import22.QueryList<any>();
    this._appEl_24.initComponent(this._Item_24_4.context,([] as any[]),compView_24);
    this._text_25 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_26 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_26,'floating','');
    this._Label_26_3 = new import23.Wrapper_Label(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_26),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'Last Name',(null as any));
    this._text_28 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_29 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_29,'formControlName','lname');
    this.renderer.setElementAttribute(this._el_29,'type','text');
    this._appEl_29 = new import3.AppElement(29,24,this,this._el_29);
    var compView_29:any = import25.viewFactory_TextInput0(this.viewUtils,this.injector(29),this._appEl_29);
    this._FormControlName_29_4 = new import24.Wrapper_FormControlName(this._ControlContainer_12_4,(null as any),(null as any),(null as any));
    this._NgControl_29_5 = this._FormControlName_29_4.context;
    this._NgControlStatus_29_6 = new import20.Wrapper_NgControlStatus(this._NgControl_29_5);
    this._TextInput_29_7 = new import25.Wrapper_TextInput(this.parentInjector.get(import28.Config),this.parentInjector.get(import36.Form),this._Item_24_4.context,this.parentInjector.get(import31.App),this.parentInjector.get(import38.Platform),new import29.ElementRef(this._el_29),this.renderer,this._Content_10_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_29_5);
    this._appEl_29.initComponent(this._TextInput_29_7.context,([] as any[]),compView_29);
    compView_29.create(this._TextInput_29_7.context,([] as any[]),(null as any));
    this._text_30 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._query_Label_24_0.reset([this._Label_26_3.context]);
    this._Item_24_4.context.contentLabel = this._query_Label_24_0.first;
    compView_24.create(this._Item_24_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_26]),
      ([] as any[]).concat([
        this._text_25,
        this._text_28,
        this._text_30
      ]
      ),
      ([] as any[]).concat([this._el_29]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_31 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_12,'control-message',(null as any));
    this._appEl_32 = new import3.AppElement(32,12,this,this._el_32);
    var compView_32:any = import26.viewFactory_ControlMessageComponent0(this.viewUtils,this.injector(32),this._appEl_32);
    this._ControlMessageComponent_32_4 = new import26.Wrapper_ControlMessageComponent();
    this._appEl_32.initComponent(this._ControlMessageComponent_32_4.context,([] as any[]),compView_32);
    compView_32.create(this._ControlMessageComponent_32_4.context,([] as any[]),(null as any));
    this._text_33 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_34,'class','item item-block');
    this._appEl_34 = new import3.AppElement(34,12,this,this._el_34);
    var compView_34:any = import21.viewFactory_Item0(this.viewUtils,this.injector(34),this._appEl_34);
    this._Item_34_4 = new import21.Wrapper_Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_34),this.renderer,this.parentInjector.get(import37.ItemReorder,(null as any)));
    this._ItemContent_34_5 = new import21.Wrapper_ItemContent();
    this._query_Label_34_0 = new import22.QueryList<any>();
    this._query_Button_34_1 = new import22.QueryList<any>();
    this._query_Icon_34_2 = new import22.QueryList<any>();
    this._appEl_34.initComponent(this._Item_34_4.context,([] as any[]),compView_34);
    this._text_35 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_36 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_36,'floating','');
    this._Label_36_3 = new import23.Wrapper_Label(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_36),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'Email',(null as any));
    this._text_38 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_39 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_39,'formControlName','email');
    this.renderer.setElementAttribute(this._el_39,'type','text');
    this._appEl_39 = new import3.AppElement(39,34,this,this._el_39);
    var compView_39:any = import25.viewFactory_TextInput0(this.viewUtils,this.injector(39),this._appEl_39);
    this._FormControlName_39_4 = new import24.Wrapper_FormControlName(this._ControlContainer_12_4,(null as any),(null as any),(null as any));
    this._NgControl_39_5 = this._FormControlName_39_4.context;
    this._NgControlStatus_39_6 = new import20.Wrapper_NgControlStatus(this._NgControl_39_5);
    this._TextInput_39_7 = new import25.Wrapper_TextInput(this.parentInjector.get(import28.Config),this.parentInjector.get(import36.Form),this._Item_34_4.context,this.parentInjector.get(import31.App),this.parentInjector.get(import38.Platform),new import29.ElementRef(this._el_39),this.renderer,this._Content_10_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_39_5);
    this._appEl_39.initComponent(this._TextInput_39_7.context,([] as any[]),compView_39);
    compView_39.create(this._TextInput_39_7.context,([] as any[]),(null as any));
    this._text_40 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._query_Label_34_0.reset([this._Label_36_3.context]);
    this._Item_34_4.context.contentLabel = this._query_Label_34_0.first;
    compView_34.create(this._Item_34_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_36]),
      ([] as any[]).concat([
        this._text_35,
        this._text_38,
        this._text_40
      ]
      ),
      ([] as any[]).concat([this._el_39]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_41 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_12,'control-message',(null as any));
    this._appEl_42 = new import3.AppElement(42,12,this,this._el_42);
    var compView_42:any = import26.viewFactory_ControlMessageComponent0(this.viewUtils,this.injector(42),this._appEl_42);
    this._ControlMessageComponent_42_4 = new import26.Wrapper_ControlMessageComponent();
    this._appEl_42.initComponent(this._ControlMessageComponent_42_4.context,([] as any[]),compView_42);
    compView_42.create(this._ControlMessageComponent_42_4.context,([] as any[]),(null as any));
    this._text_43 = this.renderer.createText(this._el_12,'\n\n        ',(null as any));
    this._el_44 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_44,'class','item item-block');
    this._appEl_44 = new import3.AppElement(44,12,this,this._el_44);
    var compView_44:any = import21.viewFactory_Item0(this.viewUtils,this.injector(44),this._appEl_44);
    this._Item_44_4 = new import21.Wrapper_Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_44),this.renderer,this.parentInjector.get(import37.ItemReorder,(null as any)));
    this._ItemContent_44_5 = new import21.Wrapper_ItemContent();
    this._query_Label_44_0 = new import22.QueryList<any>();
    this._query_Button_44_1 = new import22.QueryList<any>();
    this._query_Icon_44_2 = new import22.QueryList<any>();
    this._appEl_44.initComponent(this._Item_44_4.context,([] as any[]),compView_44);
    this._text_45 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_46 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_46,'floating','');
    this._Label_46_3 = new import23.Wrapper_Label(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_46),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_47 = this.renderer.createText(this._el_46,'Password',(null as any));
    this._text_48 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_49 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_49,'formControlName','password');
    this.renderer.setElementAttribute(this._el_49,'type','password');
    this._appEl_49 = new import3.AppElement(49,44,this,this._el_49);
    var compView_49:any = import25.viewFactory_TextInput0(this.viewUtils,this.injector(49),this._appEl_49);
    this._FormControlName_49_4 = new import24.Wrapper_FormControlName(this._ControlContainer_12_4,(null as any),(null as any),(null as any));
    this._NgControl_49_5 = this._FormControlName_49_4.context;
    this._NgControlStatus_49_6 = new import20.Wrapper_NgControlStatus(this._NgControl_49_5);
    this._TextInput_49_7 = new import25.Wrapper_TextInput(this.parentInjector.get(import28.Config),this.parentInjector.get(import36.Form),this._Item_44_4.context,this.parentInjector.get(import31.App),this.parentInjector.get(import38.Platform),new import29.ElementRef(this._el_49),this.renderer,this._Content_10_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_49_5);
    this._appEl_49.initComponent(this._TextInput_49_7.context,([] as any[]),compView_49);
    compView_49.create(this._TextInput_49_7.context,([] as any[]),(null as any));
    this._text_50 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._query_Label_44_0.reset([this._Label_46_3.context]);
    this._Item_44_4.context.contentLabel = this._query_Label_44_0.first;
    compView_44.create(this._Item_44_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_46]),
      ([] as any[]).concat([
        this._text_45,
        this._text_48,
        this._text_50
      ]
      ),
      ([] as any[]).concat([this._el_49]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_51 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._el_52 = this.renderer.createElement(this._el_12,'control-message',(null as any));
    this._appEl_52 = new import3.AppElement(52,12,this,this._el_52);
    var compView_52:any = import26.viewFactory_ControlMessageComponent0(this.viewUtils,this.injector(52),this._appEl_52);
    this._ControlMessageComponent_52_4 = new import26.Wrapper_ControlMessageComponent();
    this._appEl_52.initComponent(this._ControlMessageComponent_52_4.context,([] as any[]),compView_52);
    compView_52.create(this._ControlMessageComponent_52_4.context,([] as any[]),(null as any));
    this._text_53 = this.renderer.createText(this._el_12,'\n\n        ',(null as any));
    this._el_54 = this.renderer.createElement(this._el_12,'button',(null as any));
    this.renderer.setElementAttribute(this._el_54,'color','primary');
    this.renderer.setElementAttribute(this._el_54,'full','');
    this.renderer.setElementAttribute(this._el_54,'icon-left','');
    this.renderer.setElementAttribute(this._el_54,'ion-button','');
    this.renderer.setElementAttribute(this._el_54,'item-right','');
    this.renderer.setElementAttribute(this._el_54,'type','Submit');
    this._appEl_54 = new import3.AppElement(54,12,this,this._el_54);
    var compView_54:any = import27.viewFactory_Button0(this.viewUtils,this.injector(54),this._appEl_54);
    this._Button_54_4 = new import27.Wrapper_Button((null as any),'',this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_54),this.renderer);
    this._appEl_54.initComponent(this._Button_54_4.context,([] as any[]),compView_54);
    this._text_55 = this.renderer.createText((null as any),'\n            Submit\n        ',(null as any));
    compView_54.create(this._Button_54_4.context,[([] as any[]).concat([this._text_55])],(null as any));
    this._text_56 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._text_57 = this.renderer.createText((null as any),'\n',(null as any));
    compView_10.create(this._Content_10_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_11,
        this._el_12,
        this._text_57
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_12,'ngSubmit',this.eventHandler(this._handle_ngSubmit_12_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_12,'submit',this.eventHandler(this._handle_submit_12_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_12,'reset',this.eventHandler(this._handle_reset_12_2.bind(this)));
    const subscription_0:any = this._FormGroupDirective_12_3.context.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_12_0.bind(this)));
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    this._expr_35 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_38 = import7.UNINITIALIZED;
    this._expr_42 = import7.UNINITIALIZED;
    this._expr_43 = import7.UNINITIALIZED;
    this._expr_44 = import7.UNINITIALIZED;
    this._expr_45 = import7.UNINITIALIZED;
    this._expr_46 = import7.UNINITIALIZED;
    this._expr_47 = import7.UNINITIALIZED;
    this._expr_50 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._text_57
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import39.ToolbarTitle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ToolbarTitle_5_4.context; }
    if (((token === import40.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Navbar_3_4.context; }
    if (((token === import32.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Header_1_3.context; }
    if (((token === import41.Label) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Label_16_3.context; }
    if (((token === import42.FormControlName) && (19 === requestNodeIndex))) { return this._FormControlName_19_4.context; }
    if (((token === import43.NgControl) && (19 === requestNodeIndex))) { return this._NgControl_19_5; }
    if (((token === import44.NgControlStatus) && (19 === requestNodeIndex))) { return this._NgControlStatus_19_6.context; }
    if (((token === import45.TextInput) && (19 === requestNodeIndex))) { return this._TextInput_19_7.context; }
    if (((token === import46.Item) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._Item_14_4.context; }
    if (((token === import46.ItemContent) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._ItemContent_14_5.context; }
    if (((token === import47.ControlMessageComponent) && (22 === requestNodeIndex))) { return this._ControlMessageComponent_22_4.context; }
    if (((token === import41.Label) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Label_26_3.context; }
    if (((token === import42.FormControlName) && (29 === requestNodeIndex))) { return this._FormControlName_29_4.context; }
    if (((token === import43.NgControl) && (29 === requestNodeIndex))) { return this._NgControl_29_5; }
    if (((token === import44.NgControlStatus) && (29 === requestNodeIndex))) { return this._NgControlStatus_29_6.context; }
    if (((token === import45.TextInput) && (29 === requestNodeIndex))) { return this._TextInput_29_7.context; }
    if (((token === import46.Item) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Item_24_4.context; }
    if (((token === import46.ItemContent) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._ItemContent_24_5.context; }
    if (((token === import47.ControlMessageComponent) && (32 === requestNodeIndex))) { return this._ControlMessageComponent_32_4.context; }
    if (((token === import41.Label) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._Label_36_3.context; }
    if (((token === import42.FormControlName) && (39 === requestNodeIndex))) { return this._FormControlName_39_4.context; }
    if (((token === import43.NgControl) && (39 === requestNodeIndex))) { return this._NgControl_39_5; }
    if (((token === import44.NgControlStatus) && (39 === requestNodeIndex))) { return this._NgControlStatus_39_6.context; }
    if (((token === import45.TextInput) && (39 === requestNodeIndex))) { return this._TextInput_39_7.context; }
    if (((token === import46.Item) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._Item_34_4.context; }
    if (((token === import46.ItemContent) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._ItemContent_34_5.context; }
    if (((token === import47.ControlMessageComponent) && (42 === requestNodeIndex))) { return this._ControlMessageComponent_42_4.context; }
    if (((token === import41.Label) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._Label_46_3.context; }
    if (((token === import42.FormControlName) && (49 === requestNodeIndex))) { return this._FormControlName_49_4.context; }
    if (((token === import43.NgControl) && (49 === requestNodeIndex))) { return this._NgControl_49_5; }
    if (((token === import44.NgControlStatus) && (49 === requestNodeIndex))) { return this._NgControlStatus_49_6.context; }
    if (((token === import45.TextInput) && (49 === requestNodeIndex))) { return this._TextInput_49_7.context; }
    if (((token === import46.Item) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._Item_44_4.context; }
    if (((token === import46.ItemContent) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._ItemContent_44_5.context; }
    if (((token === import47.ControlMessageComponent) && (52 === requestNodeIndex))) { return this._ControlMessageComponent_52_4.context; }
    if (((token === import48.Button) && ((54 <= requestNodeIndex) && (requestNodeIndex <= 55)))) { return this._Button_54_4.context; }
    if (((token === import49.FormGroupDirective) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._FormGroupDirective_12_3.context; }
    if (((token === import50.ControlContainer) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._ControlContainer_12_4; }
    if (((token === import44.NgControlStatusGroup) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._NgControlStatusGroup_12_5.context; }
    if (((token === import51.Content) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._Content_10_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    const currVal_0:any = 'primary';
    this._Navbar_3_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    if (this._ToolbarTitle_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    if (this._Content_10_4.detectChangesInternal(this,this._el_10,throwOnChange)) { this._appEl_10.componentView.markAsCheckOnce(); }
    const currVal_7:any = this.context.registerForm;
    this._FormGroupDirective_12_3.check_form(currVal_7,throwOnChange,false);
    this._FormGroupDirective_12_3.detectChangesInternal(this,this._el_12,throwOnChange);
    this._NgControlStatusGroup_12_5.detectChangesInternal(this,this._el_12,throwOnChange);
    if (this._Item_14_4.detectChangesInternal(this,this._el_14,throwOnChange)) { this._appEl_14.componentView.markAsCheckOnce(); }
    this._ItemContent_14_5.detectChangesInternal(this,this._el_14,throwOnChange);
    this._Label_16_3.detectChangesInternal(this,this._el_16,throwOnChange);
    const currVal_14:any = 'fname';
    this._FormControlName_19_4.check_name(currVal_14,throwOnChange,false);
    this._FormControlName_19_4.detectChangesInternal(this,this._el_19,throwOnChange);
    this._NgControlStatus_19_6.detectChangesInternal(this,this._el_19,throwOnChange);
    const currVal_21:any = 'text';
    this._TextInput_19_7.check_type(currVal_21,throwOnChange,false);
    this._TextInput_19_7.detectChangesInternal(this,this._el_19,throwOnChange);
    const currVal_22:any = this.context.registerForm.get('fname');
    this._ControlMessageComponent_22_4.check_control(currVal_22,throwOnChange,false);
    this._ControlMessageComponent_22_4.detectChangesInternal(this,this._el_22,throwOnChange);
    if (this._Item_24_4.detectChangesInternal(this,this._el_24,throwOnChange)) { this._appEl_24.componentView.markAsCheckOnce(); }
    this._ItemContent_24_5.detectChangesInternal(this,this._el_24,throwOnChange);
    this._Label_26_3.detectChangesInternal(this,this._el_26,throwOnChange);
    const currVal_23:any = 'lname';
    this._FormControlName_29_4.check_name(currVal_23,throwOnChange,false);
    this._FormControlName_29_4.detectChangesInternal(this,this._el_29,throwOnChange);
    this._NgControlStatus_29_6.detectChangesInternal(this,this._el_29,throwOnChange);
    const currVal_30:any = 'text';
    this._TextInput_29_7.check_type(currVal_30,throwOnChange,false);
    this._TextInput_29_7.detectChangesInternal(this,this._el_29,throwOnChange);
    const currVal_31:any = this.context.registerForm.get('lname');
    this._ControlMessageComponent_32_4.check_control(currVal_31,throwOnChange,false);
    this._ControlMessageComponent_32_4.detectChangesInternal(this,this._el_32,throwOnChange);
    if (this._Item_34_4.detectChangesInternal(this,this._el_34,throwOnChange)) { this._appEl_34.componentView.markAsCheckOnce(); }
    this._ItemContent_34_5.detectChangesInternal(this,this._el_34,throwOnChange);
    this._Label_36_3.detectChangesInternal(this,this._el_36,throwOnChange);
    const currVal_32:any = 'email';
    this._FormControlName_39_4.check_name(currVal_32,throwOnChange,false);
    this._FormControlName_39_4.detectChangesInternal(this,this._el_39,throwOnChange);
    this._NgControlStatus_39_6.detectChangesInternal(this,this._el_39,throwOnChange);
    const currVal_39:any = 'text';
    this._TextInput_39_7.check_type(currVal_39,throwOnChange,false);
    this._TextInput_39_7.detectChangesInternal(this,this._el_39,throwOnChange);
    const currVal_40:any = this.context.registerForm.get('email');
    this._ControlMessageComponent_42_4.check_control(currVal_40,throwOnChange,false);
    this._ControlMessageComponent_42_4.detectChangesInternal(this,this._el_42,throwOnChange);
    if (this._Item_44_4.detectChangesInternal(this,this._el_44,throwOnChange)) { this._appEl_44.componentView.markAsCheckOnce(); }
    this._ItemContent_44_5.detectChangesInternal(this,this._el_44,throwOnChange);
    this._Label_46_3.detectChangesInternal(this,this._el_46,throwOnChange);
    const currVal_41:any = 'password';
    this._FormControlName_49_4.check_name(currVal_41,throwOnChange,false);
    this._FormControlName_49_4.detectChangesInternal(this,this._el_49,throwOnChange);
    this._NgControlStatus_49_6.detectChangesInternal(this,this._el_49,throwOnChange);
    const currVal_48:any = 'password';
    this._TextInput_49_7.check_type(currVal_48,throwOnChange,false);
    this._TextInput_49_7.detectChangesInternal(this,this._el_49,throwOnChange);
    const currVal_49:any = this.context.registerForm.get('password');
    this._ControlMessageComponent_52_4.check_control(currVal_49,throwOnChange,false);
    this._ControlMessageComponent_52_4.detectChangesInternal(this,this._el_52,throwOnChange);
    const currVal_51:any = '';
    this._Button_54_4.check_full(currVal_51,throwOnChange,false);
    const currVal_52:any = 'primary';
    this._Button_54_4.check_color(currVal_52,throwOnChange,false);
    if (this._Button_54_4.detectChangesInternal(this,this._el_54,throwOnChange)) { this._appEl_54.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_14_1.dirty) {
        this._query_Button_14_1.reset(([] as any[]));
        this._Item_14_4.context._buttons = this._query_Button_14_1;
        this._query_Button_14_1.notifyOnChanges();
      }
      if (this._query_Icon_14_2.dirty) {
        this._query_Icon_14_2.reset(([] as any[]));
        this._Item_14_4.context._icons = this._query_Icon_14_2;
        this._query_Icon_14_2.notifyOnChanges();
      }
      if (this._query_Button_24_1.dirty) {
        this._query_Button_24_1.reset(([] as any[]));
        this._Item_24_4.context._buttons = this._query_Button_24_1;
        this._query_Button_24_1.notifyOnChanges();
      }
      if (this._query_Icon_24_2.dirty) {
        this._query_Icon_24_2.reset(([] as any[]));
        this._Item_24_4.context._icons = this._query_Icon_24_2;
        this._query_Icon_24_2.notifyOnChanges();
      }
      if (this._query_Button_34_1.dirty) {
        this._query_Button_34_1.reset(([] as any[]));
        this._Item_34_4.context._buttons = this._query_Button_34_1;
        this._query_Button_34_1.notifyOnChanges();
      }
      if (this._query_Icon_34_2.dirty) {
        this._query_Icon_34_2.reset(([] as any[]));
        this._Item_34_4.context._icons = this._query_Icon_34_2;
        this._query_Icon_34_2.notifyOnChanges();
      }
      if (this._query_Button_44_1.dirty) {
        this._query_Button_44_1.reset(([] as any[]));
        this._Item_44_4.context._buttons = this._query_Button_44_1;
        this._query_Button_44_1.notifyOnChanges();
      }
      if (this._query_Icon_44_2.dirty) {
        this._query_Icon_44_2.reset(([] as any[]));
        this._Item_44_4.context._icons = this._query_Icon_44_2;
        this._query_Icon_44_2.notifyOnChanges();
      }
      this._TextInput_19_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_14_4.context.ngAfterContentInit(); }
      this._TextInput_29_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_24_4.context.ngAfterContentInit(); }
      this._TextInput_39_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_34_4.context.ngAfterContentInit(); }
      this._TextInput_49_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_44_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_54_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_3_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_3_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_10_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_10,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_8:any = this._NgControlStatusGroup_12_5.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_12,'ng-untouched',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_12_5.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_12,'ng-touched',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatusGroup_12_5.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_12,'ng-pristine',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatusGroup_12_5.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_12,'ng-dirty',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatusGroup_12_5.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_12,'ng-valid',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatusGroup_12_5.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_12,'ng-invalid',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_15:any = this._NgControlStatus_19_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_19,'ng-untouched',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_19_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_19,'ng-touched',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_19_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_19,'ng-pristine',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_19_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_19,'ng-dirty',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_19_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_19,'ng-valid',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_19_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_19,'ng-invalid',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_24:any = this._NgControlStatus_29_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_29,'ng-untouched',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = this._NgControlStatus_29_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_29,'ng-touched',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_29_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_29,'ng-pristine',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_29_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_29,'ng-dirty',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_29_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_29,'ng-valid',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_29_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_29,'ng-invalid',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_33:any = this._NgControlStatus_39_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_39,'ng-untouched',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_34:any = this._NgControlStatus_39_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementClass(this._el_39,'ng-touched',currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = this._NgControlStatus_39_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementClass(this._el_39,'ng-pristine',currVal_35);
      this._expr_35 = currVal_35;
    }
    const currVal_36:any = this._NgControlStatus_39_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementClass(this._el_39,'ng-dirty',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_37:any = this._NgControlStatus_39_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementClass(this._el_39,'ng-valid',currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_38:any = this._NgControlStatus_39_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementClass(this._el_39,'ng-invalid',currVal_38);
      this._expr_38 = currVal_38;
    }
    const currVal_42:any = this._NgControlStatus_49_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this.renderer.setElementClass(this._el_49,'ng-untouched',currVal_42);
      this._expr_42 = currVal_42;
    }
    const currVal_43:any = this._NgControlStatus_49_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this.renderer.setElementClass(this._el_49,'ng-touched',currVal_43);
      this._expr_43 = currVal_43;
    }
    const currVal_44:any = this._NgControlStatus_49_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementClass(this._el_49,'ng-pristine',currVal_44);
      this._expr_44 = currVal_44;
    }
    const currVal_45:any = this._NgControlStatus_49_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setElementClass(this._el_49,'ng-dirty',currVal_45);
      this._expr_45 = currVal_45;
    }
    const currVal_46:any = this._NgControlStatus_49_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this.renderer.setElementClass(this._el_49,'ng-valid',currVal_46);
      this._expr_46 = currVal_46;
    }
    const currVal_47:any = this._NgControlStatus_49_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_47,currVal_47)) {
      this.renderer.setElementClass(this._el_49,'ng-invalid',currVal_47);
      this._expr_47 = currVal_47;
    }
    const currVal_50:boolean = !this.context.registerForm.valid;
    if (import4.checkBinding(throwOnChange,this._expr_50,currVal_50)) {
      this.renderer.setElementProperty(this._el_54,'disabled',currVal_50);
      this._expr_50 = currVal_50;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._FormControlName_19_4.context.ngOnDestroy();
    this._TextInput_19_7.context.ngOnDestroy();
    this._FormControlName_29_4.context.ngOnDestroy();
    this._TextInput_29_7.context.ngOnDestroy();
    this._FormControlName_39_4.context.ngOnDestroy();
    this._TextInput_39_7.context.ngOnDestroy();
    this._FormControlName_49_4.context.ngOnDestroy();
    this._TextInput_49_7.context.ngOnDestroy();
    this._Content_10_4.context.ngOnDestroy();
  }
  private _handle_ngSubmit_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.OnCreateAccount(this.context.registerForm.value)) !== false);
    return (true && pd_0);
  }
  private _handle_submit_12_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_12_3.context.onSubmit($event)) !== false);
    return (true && pd_0);
  }
  private _handle_reset_12_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_12_3.context.onReset()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_RegisterPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.RegisterPage> {
  if ((renderType_RegisterPage === (null as any))) { (renderType_RegisterPage = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,styles_RegisterPage,{})); }
  return new _View_RegisterPage0(viewUtils,parentInjector,declarationEl);
}