/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './message';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import12 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import14 from 'ionic-angular/config/config';
import * as import15 from '@angular/core/src/linker/element_ref';
import * as import16 from 'ionic-angular/navigation/view-controller';
import * as import17 from 'ionic-angular/components/app/app';
import * as import18 from 'ionic-angular/util/keyboard';
import * as import19 from '@angular/core/src/zone/ng_zone';
import * as import20 from 'ionic-angular/components/tabs/tabs';
import * as import21 from 'ionic-angular/components/navbar/navbar';
import * as import22 from 'ionic-angular/components/toolbar/toolbar';
import * as import23 from 'ionic-angular/components/content/content';
export class Wrapper_MessagePage {
  context:import0.MessagePage;
  changed:boolean;
  constructor(p0:any) {
    this.changed = false;
    this.context = new import0.MessagePage(p0);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_MessagePage_Host:import2.RenderComponentType = (null as any);
class _View_MessagePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _MessagePage_0_4:Wrapper_MessagePage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MessagePage_Host0,renderType_MessagePage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-message',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_MessagePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._MessagePage_0_4 = new Wrapper_MessagePage(this.parentInjector.get(import8.NavController));
    this._appEl_0.initComponent(this._MessagePage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._MessagePage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.MessagePage) && (0 === requestNodeIndex))) { return this._MessagePage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MessagePage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_MessagePage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_MessagePage_Host === (null as any))) { (renderType_MessagePage_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_MessagePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const MessagePageNgFactory:import10.ComponentFactory<import0.MessagePage> = new import10.ComponentFactory<import0.MessagePage>('page-message',viewFactory_MessagePage_Host0,import0.MessagePage);
const styles_MessagePage:any[] = ([] as any[]);
var renderType_MessagePage:import2.RenderComponentType = (null as any);
class _View_MessagePage0 extends import1.AppView<import0.MessagePage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import11.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import12.Wrapper_Navbar;
  _text_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  /*private*/ _appEl_7:import3.AppElement;
  _Content_7_4:import13.Wrapper_Content;
  _text_8:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MessagePage0,renderType_MessagePage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import11.Wrapper_Header(this.parentInjector.get(import14.Config),new import15.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import16.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import12.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import12.Wrapper_Navbar(this.parentInjector.get(import17.App),this.parentInjector.get(import16.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import14.Config),new import15.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_4])
    ]
    ,(null as any));
    this._text_5 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._text_6 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_7 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_7,'padding','');
    this._appEl_7 = new import3.AppElement(7,(null as any),this,this._el_7);
    var compView_7:any = import13.viewFactory_Content0(this.viewUtils,this.injector(7),this._appEl_7);
    this._Content_7_4 = new import13.Wrapper_Content(this.parentInjector.get(import14.Config),new import15.ElementRef(this._el_7),this.renderer,this.parentInjector.get(import17.App),this.parentInjector.get(import18.Keyboard),this.parentInjector.get(import19.NgZone),this.parentInjector.get(import16.ViewController,(null as any)),this.parentInjector.get(import20.Tabs,(null as any)));
    this._appEl_7.initComponent(this._Content_7_4.context,([] as any[]),compView_7);
    this._text_8 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_7.create(this._Content_7_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._text_8]),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._Navbar_3_4.context; }
    if (((token === import22.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._Header_1_3.context; }
    if (((token === import23.Content) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Content_7_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    if (this._Content_7_4.detectChangesInternal(this,this._el_7,throwOnChange)) { this._appEl_7.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this._Navbar_3_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_3_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_7_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_7,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_7_4.context.ngOnDestroy();
  }
}
export function viewFactory_MessagePage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.MessagePage> {
  if ((renderType_MessagePage === (null as any))) { (renderType_MessagePage = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_MessagePage,{})); }
  return new _View_MessagePage0(viewUtils,parentInjector,declarationEl);
}